### ISSUE TITLE
运行h5提示如下，该怎么解决呢，我的运行脚本就简单的使用默认的h5启动

### ISSUE THREAD

**Issue by LCH7700** [lqc520/uniapp-plugin#1]
Cannot start process, the working directory '/Applications/HBuilderX.app/plugins/uniapp-cli' does not exist

**Comment by LCH7700** [comment]
配置如下：
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/37178705/233602837-db1eebc0-438f-430c-b514-f8f0fbdced1d.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/37178705/233602977-50752880-2940-46f7-8e4b-ae208155c848.png">

运行结果如下：
<img width="485" alt="image" src="https://user-images.githubusercontent.com/37178705/233602880-da0d7d08-c676-4cec-82f9-d4db662dc2a8.png">

**Comment by lqc520** [comment]
了解 苹果电脑我这边适配一下

**Comment by LCH7700** [comment]
> 

感谢，期待你的好消息

**Comment by lqc520** [comment]
[适配好了 你试试](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.2/Uniapp-1.0.2.zip)

**Comment by lqc520** [comment]
适配好了 你试试 [点击下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.2/Uniapp-1.0.2.zip)

**Comment by lqc520** [comment]
等插件官方审核过后也可以在插件市场升级哈

**Comment by LCH7700** [comment]
已测试，完美运行！感谢🙏
