### ISSUE TITLE
编译项目卡住

### ISSUE THREAD

**Issue by fl1906** [lqc520/uniapp-plugin#100]
**描述错误**
对bug的简明描述.
编译项目卡住，无法停止
还请添加显示问题的屏幕截图.
![image](https://github.com/lqc520/uniapp-plugin/assets/73702449/3699bbd2-d531-48e3-ad3a-8dff43e01f5b)

**使用的插件版本**
Uniapp Tool: 最新版
vue: 2
project: /hbx
ide: IDEA

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by lqc520** [comment]
我给你远程看一下？

**Comment by zimistan** [comment]
我也出现了相同的问题，有些项目甚至编译一次之后，后面有改动都不会再编译了。我的邮箱：a__dil@outlook.com

**Comment by lqc520** [comment]
加我微信吧 readme 有 看一下是啥情况

**Comment by zimistan** [comment]
如果是编译的微信小程序项目，那就需要在小程序开发工具的设置中打开服务端口开关才能正常编译。

**Comment by lqc520** [comment]
不行的自己用hbx 运行一遍 还不行的再来反馈
