### ISSUE TITLE
可以对老版本的webstorm提供一下支持吗？

### ISSUE THREAD

**Issue by Si-jiyuan** [lqc520/uniapp-plugin#101]
目前使用的webstorm版本为：2021.2.2 ，无法使用此插件支持开发，希望开发者可以考虑一下对老版本的webstorm进行兼容，感谢

The current version of webstorm being used is 2021.2.2, and this plugin cannot support development. We hope developers can consider compatibility with older versions of webstorm. Thank you

**Comment by lqc520** [comment]
建议升级到新版本 现在天朝版本可以支持23.* 自己百度一下 不用老版本
