### ISSUE TITLE
easycom跳转有误

### ISSUE THREAD

**Issue by lCSSl** [lqc520/uniapp-plugin#102]
**描述错误**

在不同项目中用同样的uniapp的uni_modules插件（easycom的UI组件）
会跳转至其他项目路径下相同名字的组件

<img width="1078" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/77599000/c5b7cf4f-0abd-47c1-be5c-e37d934852c8">

**使用的插件版本**
Uniapp Tool: 1.0.13-231.2
vue: 3
project: cli-ts
ide: WebStorm 2023.3.x

**环境**
提供更多的信息:
系统:  macOS Sonoma

**如何重现**
重现行为的步骤:
1. 禁用插件
2. 启动插件
3. 打开第一个项目
4. ctrl+左键组件（正确跳转）
5. 打开第二个项目
7. ctrl+左键组件 （跳转至第一个项目的组件）
8. 如没复现，重启webstorm后从第三步开始

https://github.com/lqc520/uniapp-plugin/assets/77599000/b12e0cf9-65a7-4a90-ae77-33b1bf73b245

**预期行为**
正确跳转至本项目的UI插件

**Comment by lqc520** [comment]
你确定你的uni_module 有这个组件 没有这个组件才会去找缓存历史的

**Comment by lCSSl** [comment]
> 你确定你的uni_module 有这个组件 没有这个组件才会去找缓存历史的

是的，项目是拷贝的

**Comment by lqc520** [comment]
你加我微信 我远程给你看一下 正常是不会的

**Comment by lCSSl** [comment]
好的，微信号发一下

**Comment by lqc520** [comment]
主页

**Comment by lCSSl** [comment]
> 主页

嗯嗯，加了
