### ISSUE TITLE
2024.1版本类型报错

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#103]
**描述错误**
最新版本 uni原生view组件报类型错误

![报错](https://github.com/lqc520/uniapp-plugin/assets/29171233/90785a41-b4bb-4165-8475-256fb6ffda4c)

**使用的插件版本**
Uniapp Tool: 1.0.13-231.2
vue: 3 
project: cli-ts
ide: WebStorm 2024.1 

**环境**
 win11

**预期行为**
和之前版本一样不要报错

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/2528ce5e-0d25-4fa1-b7e2-398a5402530d)
是不兼容241

**Comment by lqc520** [comment]
我近期适配一下最近版本哈

**Comment by jasonHG** [comment]
好的,感谢

**Comment by lqc520** [comment]
你加我微信 在主页有 我给你远程看一下 我ide升级到241 我看不影响功能

**Comment by jasonHG** [comment]
**这样设置一下就好了**

![问题修复](https://github.com/lqc520/uniapp-plugin/assets/29171233/899ac43d-307f-4942-8dde-36d2bd811017)
