### ISSUE TITLE
在import导入路径中使用@绝对路径无法准确识别

### ISSUE THREAD

**Issue by uselness** [lqc520/uniapp-plugin#104]
**描述错误**
对bug的简明描述.
在<script>标签中，使用import导入时使用@符号进行绝对路径导入，无法准确识别文件路径

**使用的插件版本**
Uniapp Tool: 1.0.14
vue: 2
project: hbx
ide: WebStorm 2024.1 

**环境**
提供更多的信息:
比如:  win11
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
在vue文件中，<script>标签中使用import导入文件，路径为@符号绝对路径时，未能准确识别文件路径

**预期行为**
能准确识别绝对路径导入的文件

**Comment by lqc520** [comment]
带图

**Comment by lqc520** [comment]
241版本的vue官方插件有点问题

**Comment by uselness** [comment]
> 带图

![image](https://github.com/lqc520/uniapp-plugin/assets/29937108/3feffc68-257d-4464-a1ae-940b393b1f15)

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/eb12ab2e-b00b-4093-aec0-602733099d7c)
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/5ac33eb5-7859-4548-a1b0-0e32044a4382)
我这边测试都是正常 hbx2 hbx3

**Comment by lqc520** [comment]
你可以尝试配置一下 tsconfig 或者jsconfig 
![6f21cda7d724c1bbe42512b77b99027](https://github.com/lqc520/uniapp-plugin/assets/33248612/726640fa-c13b-4a78-943f-197dadb30004)

**Comment by lqc520** [comment]
或者ide.config.js
System.config({
  "paths": {
    "@/*": "./*"
  }
})

**Comment by uselness** [comment]
> ![image](https://private-user-images.githubusercontent.com/33248612/324313663-eb12ab2e-b00b-4093-aec0-602733099d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTYwMDEsIm5iZiI6MTcxMzc1NTcwMSwicGF0aCI6Ii8zMzI0ODYxMi8zMjQzMTM2NjMtZWIxMmFiMmUtYjAwYi00MDkzLWFlYzAtNjAyNzMzMDk5ZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGQ1ZmEzYTk1MmExZjVmZDVhZjIzYjhlMzYzOGIxMmU4OGEyYTdhODJiNDQyNDY4YTk0N2QxNGQwMThjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AdQ9sY_dIxc2yWXxK1ukbAOVKUGbGg3yLwbufn7OT5Q) ![image](https://private-user-images.githubusercontent.com/33248612/324313748-5ac33eb5-7859-4548-a1b0-0e32044a4382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTYwMDEsIm5iZiI6MTcxMzc1NTcwMSwicGF0aCI6Ii8zMzI0ODYxMi8zMjQzMTM3NDgtNWFjMzNlYjUtNzg1OS00NTQ4LWExYjAtMGUzMjA0NGE0MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAzMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMjVhMGNjYmIwYTE2MWRiMDI1N2FhZWYzZjk1NTE5NzBmZjdiY2Y2YmQzNGVhOTZlMmRlYzc3NTczYWYwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVYwgmqeBOhvjKRcGqhcJ0G0QulksYe451PLvHxtCnw) 我这边测试都是正常 hbx2 hbx3

我是使用hx新建项目的，没有使用cli新建项目

**Comment by lqc520** [comment]
我这边也是测试的也是hbx项目

**Comment by lqc520** [comment]
cli 结构不一样 是在src里面的 有package.json

**Comment by lqc520** [comment]
你可以加我 我拉你进群 有啥问题好沟通
