### ISSUE TITLE
pages.json中的path无法跳转

### ISSUE THREAD

**Issue by chengkni** [lqc520/uniapp-plugin#106]
**描述错误**
第一次提issue。格式有问题多请见谅。
我看插件主页介绍支持json中的path跳转。我装完好像没发跳转。

**使用的插件版本**
Uniapp Tool: 1.0.14-241.1
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 2024.1.1 

**环境**
macOS和Windows11都试过了，依然无法跳转。

**如何重现**
重现行为的步骤:
通过pages.json中的path字段无法跳转到指定的路径。

**预期行为**
安卓技术栈，最近想学前端，我不太清楚项目配置问题还是什么原因。公众号群二维码已失效。所以想通过issues寻求帮助。
看了历史issues，刚刚又试了一下，页面中的url也无法跳转。

<img width="896" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/10266492/04e6f589-f7d8-4a3d-9ca0-78d4044b9111">

**Comment by lqc520** [comment]
自定义封装的路径无法识别跳转哈  uni.navigateTo({
            url: '/pages/agreement/agreement'
        }) 这种的才会提示路径 和跳转

**Comment by lqc520** [comment]
二维码更新了

**Comment by chengkni** [comment]
> 自定义封装的路径无法识别跳转哈 uni.navigateTo({ url: '/pages/agreement/agreement' }) 这种的才会提示路径 和跳转

<img width="848" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/10266492/333d9e89-47fb-42a8-b938-03b68e1d79ed">
试了一下还是不行，nvue和vue页面都没法跳转。

**Comment by lqc520** [comment]
这个是你自己环境问题 无法处理 这个功能我们自己也在天天使用 子包和主包都是可以正常跳转的 但是目前的版本只能识别到vue页面
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/3468ad46-0f95-4708-8d48-fe2f6a595946)

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/0b808b68-2a66-4f0a-9213-211f90716d06)

**Comment by lqc520** [comment]
针对nvue的识别和跳转下个版本会上线

**Comment by chengkni** [comment]
> 这个是你自己环境问题 无法处理 这个功能我们自己也在天天使用 子包和主包都是可以正常跳转的 但是目前的版本只能识别到vue页面 ![image](https://private-user-images.githubusercontent.com/33248612/326170150-3468ad46-0f95-4708-8d48-fe2f6a595946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTM1MTUsIm5iZiI6MTcxNDIxMzIxNSwicGF0aCI6Ii8zMzI0ODYxMi8zMjYxNzAxNTAtMzQ2OGFkNDYtMGY5NS00NzA4LThkNDgtZmUyZjZhNTk1OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEwMjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDdiZDJlOTlhMzQ5YmFlODA2YjJiY2U3NmRkYWYyOTczMDUwODQ4ZmQ3YWQ0OTlmYjJlZDViZjZkZjVmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HkgY91o6IWfpSHzqe26f4SMDgPceWAQy7LJgb2SnN5I)

<img width="754" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/10266492/a9309a98-12bb-4714-80c3-664ac88fd4de">

子包跳转没问题。主包的pages目录下边是可以正常跳转的。但是非pages目录就没法跳转了。

**Comment by lqc520** [comment]
非pages 目录是啥意思？

**Comment by lqc520** [comment]
只能跳转 xxx.vue页面 不能跳转目录

**Comment by chengkni** [comment]
> 非pages 目录是啥意思？


src/pages目录下边的文件都可以跳，但是非pages目录。如我上边的截图，src/demo这个目录下边的就没法跳转。
但是我subPackages下配置的都可以跳。
就"pages": []这里边只能可以跳到src/pages下的目录。

**Comment by lqc520** [comment]
和这个没关系 src/demo 注册子包了吗？

**Comment by lqc520** [comment]
注册了就支持跳转

**Comment by chengkni** [comment]
> 注册了就支持跳转


<img width="1347" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/10266492/6c7e75b5-9cc3-4190-bf57-0d317fadc4c1">

macOS和Windows11都试过了。不行。

**Comment by lqc520** [comment]
你应该是刚学uniapp 没多久吧

**Comment by lqc520** [comment]
你可以试试其他插件 uniappSuport
