### ISSUE TITLE
CPU飚高100%，IDE直接卡死

### ISSUE THREAD

**Issue by konwww** [lqc520/uniapp-plugin#107]
<!--
您不需要删除此评论部分，它在问题页面上是不可见的.

## 通用说明

**描述错误**
在未运行项目的情况下，编写uniapp代码，IDEA直接CPU占用100%，当切出IDEA窗口，CPU占用率直接下降，如果切回，CPU占用率立马回升，停用插件后就恢复了正常

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: 1.0.15-241.1
vue: 2
project: hbx
ide: IDEA UTL 2024.1 

**环境**
Win10

**如何重现**
重现行为的步骤:
安装插件并启用就可以复现

**预期行为**
CPU占用正常

**Comment by lqc520** [comment]
哪个版本

**Comment by konwww** [comment]
> 哪个版本

我写的描述在提交的时候全部消失了。。。，插件版本：1.0.15-241.1 IDE是IDEA 2024.1 系统是Win10，项目是用的ruoyi 移动版

![image](https://github.com/lqc520/uniapp-plugin/assets/34157376/4e396187-29bd-4960-8b57-5c082e916dfe)

**Comment by konwww** [comment]
> 哪个版本

这是若依项目地址：http://doc.ruoyi.vip/ruoyi-app/

**Comment by konwww** [comment]
> 哪个版本

安装插件后，等待IDE索引和缓存构建完毕，再修改代码，写代码的时候相对要没那么卡顿，但是如果是删除代码的时候就会变得很卡，CPU占用率直接100%，如果切出IDE窗口，CPU占用率会很快恢复正常，如果切回继续编辑代码，CPU又会马上提高占用率

**Comment by guidedmy** [comment]
你退回到1.0.14版本试试

**Comment by konwww** [comment]
> 你退回到1.0.14版本试试

好的，我尝试一下

**Comment by guidedmy** [comment]
还可以关闭代码提示 测试一下 或者禁用插件试一下 
![image](https://github.com/lqc520/uniapp-plugin/assets/131140161/2e8c9d0f-90cc-48c0-b99d-f539e734e357)
我这边测试了一下没啥问题 但是1.0.15 增加了对nvue uvue的支持 可能会更吃性能一点点 但是也不应该 你排查一下

**Comment by guidedmy** [comment]
你是不是子项目放一起 改用webstorm 试试 或者单独打开 这个也看你的设备性能

**Comment by konwww** [comment]
> 还可以关闭代码提示 测试一下 或者禁用插件试一下 ![image](https://private-user-images.githubusercontent.com/131140161/326661919-2e8c9d0f-90cc-48c0-b99d-f539e734e357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDk4NzIsIm5iZiI6MTcxNDQ0OTU3MiwicGF0aCI6Ii8xMzExNDAxNjEvMzI2NjYxOTE5LTJlOGM5ZDBmLTkwY2MtNDhjMC1iOTlkLWY1MzllNzM0ZTM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwMzU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmMxNDBkMmU1YjEwMDk5Mzk5ZjBkNjcwNWE0ZDhlZGRiMDAyMTUyZjMzYzIzNDdmYTNmNjJhYmE4YTJkMTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1vlkAf5JZvMiVpfq465b3eVVIRxSyLi-agK2LC0WDcw) 我这边测试了一下没啥问题 但是1.0.15 增加了对nvue uvue的支持 可能会更吃性能一点点 但是也不应该 你排查一下

测试webstorm没有问题，1.0.14和15都测试了，CPU占用正常；IDEA那边卸载插件后正常，插件版本14和15都一样有卡顿的问题，关闭代码提示和打卡“卡顿打开”选项后好一些，卡顿减弱了
