### ISSUE TITLE
uniapp 条件编译 运行模式如何添加

### ISSUE THREAD

**Issue by pglin66** [lqc520/uniapp-plugin#108]
自定义的条件编译  uni app script 里面的如何添加运行配置
"uni-app": {
        // 扩展配置
        "scripts": {
                // 自定义编译平台配置，可通过 cli 方式调用
                "custom-platform": {
                        // 会显示在 HBuilderX 中的 <运行/发行> 菜单中
                        "title": "自定义扩展名称", 
                        // 运行到的目标浏览器，仅当 UNI_PLATFORM 为 h5 时有效
                        "browser": "",
                        // 环境变量
                        "env": {
                                // 基准平台
                                "UNI_PLATFORM": "",
                                // ... 其他自定义环境变量
                                "MY_TEST": ""
                         },
                        // 自定义条件编译
                        "define": {
                                // 自定义条件编译常量，建议为大写，代码中也是以此代码作为条件编译
                                "CUSTOM-CONST": true
                        }
                }
        }    
}

**Comment by lqc520** [comment]
不支持
