### ISSUE TITLE
能否支持在page.json中配置的easycom规则

### ISSUE THREAD

**Issue by jiawei5807** [lqc520/uniapp-plugin#109]
![image](https://github.com/lqc520/uniapp-plugin/assets/101109349/7148ccef-1acf-4ee8-96f7-26f8d79c3baf)
这种情况下，目前在组件中没有识别出来

**Comment by lqc520** [comment]
目前不支持 只识别标准easycom组件

**Comment by lqc520** [comment]
[Uniapp-1.0.16-241.4.zip](https://github.com/user-attachments/files/17478241/Uniapp-1.0.16-241.4.zip)
支持了
