### ISSUE TITLE
条件编译自动折叠，可以关闭吗，或者加一个是否自动折叠的开关

### ISSUE THREAD

**Issue by weiminghaoo** [lqc520/uniapp-plugin#110]
**是关于什么的?**

条件编译自动折叠，可以关闭吗，或者加一个是否自动折叠的开关

**我们需要它的原因是什么?**

默认折叠，一眼看不到代码，每次都需要手动点击

**Comment by lqc520** [comment]
可以 这个小事 下个版本发布

**Comment by lqc520** [comment]
[Uniapp.zip](https://github.com/user-attachments/files/15832720/Uniapp.zip)
