### ISSUE TITLE
您好，发现插件市场显示更新，但是没有更新日志，冒味问一下修复哪些功能呢？

### ISSUE THREAD

**Issue by sunpm** [lqc520/uniapp-plugin#111]
<img width="956" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/35005831/443eefc6-4f4d-406c-94d6-b02899693590">
<img width="453" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/35005831/9b48be3f-cce6-4593-9ee3-93d1e72123ed">

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/62d51e68-589d-438d-b71e-c31eb3ffad2b)
修复了一些问题 之前有些判断是否uniapp启用的 因为延迟判断 导致一些功能未启用
