### ISSUE TITLE
WebStorm uniapp tool 运行"WX_DEV" 时出错 HbuilderX工具目录配置错误

### ISSUE THREAD

**Issue by DolphinHome** [lqc520/uniapp-plugin#112]
**描述错误**
WebStorm uniapp tool 运行"WX_DEV" 时出错 HbuilderX工具目录配置错误
![image](https://github.com/lqc520/uniapp-plugin/assets/43274422/d12b2a4b-72b5-4ff2-823d-34e5c7ca9f07)
![image](https://github.com/lqc520/uniapp-plugin/assets/43274422/64d5d5db-bc36-42e0-8bf6-2305fda70656)
![image](https://github.com/lqc520/uniapp-plugin/assets/43274422/2fbeb31e-4b59-4f57-b8d8-0116b28fb690)

**使用的插件版本**
Uniapp Tool: 1.0.13-231.2
vue: 2
project: cli-js
ide: WebStorm 2023.3.7
HBuilderX 4.15
微信开发者工具：Stable 1.06.2405020

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
1. 新加 uniapp 启动执行报错

**预期行为**
如何正常使用

**Comment by lqc520** [comment]
按提示操作 配置的是目录 不是执行exe
