### ISSUE TITLE
如何配置项目的启动目录（Hubilder创建的项目，非脚本创建的项目）

### ISSUE THREAD

**Issue by Source-Roc** [lqc520/uniapp-plugin#113]
#### 一个总的项目：，里面包含三个子项目
- 一个基于Vue2的管理项目
- 一个基于Vue2的官网页面项目
- 一个Java服务后端项目
- 一个使用Hubilder创建的UniApp项目

如何对子项目设置UniApp启动

**Comment by lqc520** [comment]
会自动识别

**Comment by Source-Roc** [comment]
找到地方了，需要打开那个子项目识别，我之前没有打开，感谢！
