### ISSUE TITLE
无src目录情况下，@路径跳转失效

### ISSUE THREAD

**Issue by franciewang** [lqc520/uniapp-plugin#115]
![image](https://github.com/lqc520/uniapp-plugin/assets/30165596/e8c8b64b-8a65-44f0-a5cd-fb4a22e36e2d)

**Comment by lqc520** [comment]
删除.idea 重新打开项目

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/b93a2efd-490c-4e40-9dae-cfee48c09744)
我这边没啥问题

**Comment by franciewang** [comment]
> 删除.idea 重新打开项目

刚试过确实不好用，缓存也清了好几次，原因未知

**Comment by lqc520** [comment]
使用哪个版本

**Comment by lqc520** [comment]
是不是最新版

**Comment by franciewang** [comment]
> 是不是最新版

v1.0.16，应该就是最新的，我这暂时没有需要更新的提示

**Comment by franciewang** [comment]
我怀疑你们寻找路径的时候，@在没有其他配置的情况下，默认是替代的 ”src“，但是如果项目没有src 就会有问题

**Comment by lqc520** [comment]
no 是你自己环境问题 
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/3cdf37d7-7b41-47ae-a751-9274bd6fe05e)

**Comment by lqc520** [comment]
我这边其他项目啥的也是正常的

**Comment by curescode** [comment]
最新版1.0.16会导致在项目中无法正常识别@别名，会提示未安装模块。如果卸载插件，手动安装旧版本，如1.0.15，重启项目就会正常识别，但是注意下载文件不能放在plugins目录下，否则重启会卡死在加载项目文件阶段，webstorm版本2024.1.1-2024.1.5均是这个问题。更多版本就没试了

**Comment by cnguu** [comment]
刚在市场安装，webstorm2023.3.7版本使用1.0.13可以正常识别路径，没收到1.0.16更新，webstorm版本2024后面的版本本身就卡，低配机尤其明显，我都不敢更新

**Comment by cnguu** [comment]
@FrancieWang 看下试试
![image](https://github.com/user-attachments/assets/07f90555-5c16-47f0-92c9-a81c0103b102)

**Comment by lqc520** [comment]
新版本已修复
