### ISSUE TITLE
运行出错  com.google.gson.stream.MalformedJsonException: Use JsonReader.setlenient(true)

### ISSUE THREAD

**Issue by brisk21** [lqc520/uniapp-plugin#117]
运行出错
 com.google.gson.stream.MalformedJsonException: Use JsonReader.setlenient(true) to accept malformed JSON at line 298 column 2 path $
![image](https://github.com/user-attachments/assets/2fab48b2-a72f-4462-ac04-9073e6565f6b)

配置正常的
![image](https://github.com/user-attachments/assets/98e24536-b0c9-4a1a-b64e-8aa5cfad5f9d)

**Comment by lqc520** [comment]
mainfest.json 不是正常的格式 或者有注释 解析有问题&nbsp;



---原始邮件---
发件人: "Brisk ***@***.***&gt;
发送时间: 2024年8月4日(周日) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lqc520/uniapp-plugin] 运行出错  com.google.gson.stream.MalformedJsonException: Use JsonReader.setlenient(true) (Issue #117)




 
运行出错
 com.google.gson.stream.MalformedJsonException: Use JsonReader.setlenient(true) to accept malformed JSON at line 298 column 2 path $
 image.png (view on web)
 
配置正常的
 image.png (view on web)
