### ISSUE TITLE
能否支持自定义启动页面

### ISSUE THREAD

**Issue by EmptyDreams** [lqc520/uniapp-plugin#12]
现在使用插件调试插件的时候，每一次修改页面内容后微信的开发工具都会回到启动页面，还需要手动点回到当前正在编辑的页面。
不知道插件能否支持修改后还回到当前正在修改的页面。
我查看了微信的文档，微信的开发工具好像不支持跳转页面？
但是我觉得这个功能还是有办法实现的，通过临时修改 `app.json` 中的首页可以让微信回到当前页面。
不过插件应该是直接调用的 npm 插件，不知道能不能做到修改 `app.json`。

**Comment by lqc520** [comment]
1、可以添加这个 就是小程序自带的添加编译模式
	// #todo 为什么要注释condition下代码？
	// IOS plus.runtime.arguments 添加 condition节点后， 框架会修改 runtime.arguments
	// 会影响什么功能？
	//    -在h5中唤醒app会一直返回默认值 {"name":"","path":"","query":"","id":0}
	"condition": { //模式配置，仅开发期间生效
		// "current": 0, //当前激活的模式(list 的索引项)
		// "list": [{
		// 	"name": "", //模式名称
		// 	"path":"", //启动页面，必选
		// 	"query": "" //启动参数，在页面的onLoad函数里面得到
		// }]
	}
2、开发时用h5预览（不编译小程序）

**Comment by EmptyDreams** [comment]
> 1、可以添加这个 就是小程序自带的添加编译模式 // #todo 为什么要注释condition下代码？ // IOS plus.runtime.arguments 添加 condition节点后， 框架会修改 runtime.arguments // 会影响什么功能？ // -在h5中唤醒app会一直返回默认值 {"name":"","path":"","query":"","id":0} "condition": { //模式配置，仅开发期间生效 // "current": 0, //当前激活的模式(list 的索引项) // "list": [{ // "name": "", //模式名称 // "path":"", //启动页面，必选 // "query": "" //启动参数，在页面的onLoad函数里面得到 // }] } 2、开发时用h5预览（不编译小程序）

好的好的，没注意到 uniapp 还有这个配置。
