### ISSUE TITLE
启用插件后，文件时会一直卡在Analyzing的状态

### ISSUE THREAD

**Issue by FanHua1992** [lqc520/uniapp-plugin#122]
**描述错误**
启用插件后，文件时会一直卡在Analyzing的状态

![image](https://github.com/user-attachments/assets/8bfe404a-4e9d-44b5-9aed-f9b3d468aabc)

**使用的插件版本**
Uniapp Tool: 1.0.16-241.2
vue: 2
project: cli-js
ide: WebStorm 2024.2.3

**环境**
提供更多的信息:
比如:  win10
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
启用插件后，文件时会一直卡在Analyzing的状态，造成方法不能跳转，标签不能点击，不能链接到使用地方等。禁用插件后回复正常，上个版本无问题

**Comment by DamnCrab** [comment]
同样的问题

**Comment by lqc520** [comment]
上个版本 是指1.0.16.1 吗

**Comment by FanHua1992** [comment]
> 上个版本 是指1.0.16.1 吗

从这个页面下载了最新版本的1.0.16-241.1是可以使用的
https://plugins.jetbrains.com/plugin/21470-uniapp-tool/versions/stable

**Comment by lqc520** [comment]
已修复

**Comment by lqc520** [comment]
感谢反馈

**Comment by lqc520** [comment]
[Uniapp-1.0.16-241.3.zip](https://github.com/user-attachments/files/17388744/Uniapp-1.0.16-241.3.zip)
