### ISSUE TITLE
希望支持2024.3~；vue项目的template里面还是会提示uni相关的组件和属性，希望在非uni项目下支持禁用uni相关提示

### ISSUE THREAD

**Issue by xiaofei3062** [lqc520/uniapp-plugin#128]
希望支持2024.3~；vue项目的template里面还是会提示uni相关的组件和属性，希望在非uni项目下支持禁用uni相关提示

**Comment by xiaofei3062** [comment]
最好提供个配置项，启用禁用插件，这样在vue项目可以完全禁用插件相关功能

**Comment by lqc520** [comment]
近期会适配 243版本 api改动较大  除了 uniapp的官方组件会提示 其他不会吧 这个后面看一下怎么处理

**Comment by lqc520** [comment]
https://plugins.jetbrains.com/plugin/21470-uniapp-tool/versions/stable/635198
