### ISSUE TITLE
该更新了，idea243了，提示不支持

### ISSUE THREAD

**Issue by GeniusJerry** [lqc520/uniapp-plugin#129]
**描述错误**
对bug的简明描述.

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: x.x.x 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 202x.x.x 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by gxh2517** [comment]
自己改下就行
右键用解压缩程序打开 找到META-INF下面的plugin.xml
修改成和自己idea相同的版本
![image](https://github.com/user-attachments/assets/e65379ad-78a6-41e6-bacd-33eef39b7efe)

![image](https://github.com/user-attachments/assets/a7cd4772-7191-4113-8f58-8b76f3b56d76)
```xml
<idea-plugin>
  <version>1.0.16-241.6</version>
  <idea-version since-build="243.21565.193" until-build="243.*" />
```

现在就支持了
![image](https://github.com/user-attachments/assets/d5b999b1-ab35-4753-8791-03ab7cd5b1a2)

**Comment by lqc520** [comment]
近期会适配 243版本 api改动较大  改版本号的方式 只能安装的上 但是功能没有适配哦

**Comment by gxh2517** [comment]
我也是江湖救急，现在暂时能用

**Comment by lqc520** [comment]
https://plugins.jetbrains.com/plugin/21470-uniapp-tool/versions/stable/635198

**Comment by gxh2517** [comment]
周末还不忘加班搞，真是太良心了
