### ISSUE TITLE
有关 HBuilderX 插件的问题

### ISSUE THREAD

**Issue by EmptyDreams** [lqc520/uniapp-plugin#13]
我在 HBuilderX 中安装了 `uni-popup` 插件，插件确实识别出来我安装了这个插件，也能进行自动补全，但是在微信小程序中预览时却报错说找不到组件。

报错内容如下：

```
Component is not found in path "uni_modules/uni-popup/components/uni-popup-dialog/uni-popup-dialog" (using by "pages/user/optional")(env: Windows,mp,1.06.2303220; lib: 2.31.1)
Component is not found in path "uni_modules/uni-popup/components/uni-popup/uni-popup" (using by "pages/user/optional")(env: Windows,mp,1.06.2303220; lib: 2.31.1)
```

我的 vue 内容如下（删除了无关内容）：

```
<template>
    <uni-popup type="dialog">
        <uni-popup-dialog type="warn" cancelText="关闭" confirmText="同意" title="通知" content="欢迎使用 uni-popup!"
                          @close="console.log('c')" @confirm="console.log('co')"/>
    </uni-popup>
</template>
```

我检查了一下我的目录，报错中提到的文件目录确实是存在的，不知道这是哪里除了问题。

**Comment by EmptyDreams** [comment]
补充一下生成的微信小程序的文件目录：
1. @/pages/user/optional.json:
  ```
   {
     "navigationBarTitleText": "账户设置",
     "navigationStyle": "default",
     "usingComponents": {
       "state-link": "../../components/StateLink",
       "uni-popup-dialog": "../../uni_modules/uni-popup/components/uni-popup-dialog/uni-popup-dialog",
       "uni-popup": "../../uni_modules/uni-popup/components/uni-popup/uni-popup"
     }
   }
   ```

2. @\uni_modules\uni-popup\components\uni-popup\uni-popup.json
3. @\uni_modules\uni-popup\components\uni-popup-dialog\uni-popup-dialog.json
4. @\uni_modules\uni-transition\components\uni-transition\uni-transition.json

**Comment by lqc520** [comment]
我这边测试了一下 没啥问题  请提供更多信息 vue版本 cli还是hx项目

**Comment by EmptyDreams** [comment]
> 我这边测试了一下 没啥问题 请提供更多信息 vue版本 cli还是hx项目

说起来也奇怪，昨天我一直报错，今天我也复现不出来了，代码一个字没改。

**Comment by lqc520** [comment]
那可能是微信ide的问题

**Comment by EmptyDreams** [comment]
> 那可能是微信ide的问题

另外我写 JS 的时候会有非常明显且频繁的卡顿，关闭 UniappTool 后卡顿消失，这个卡顿能否改善一下？

**Comment by lqc520** [comment]
因为我们这边没有出现过这个问题 麻烦提供更多信息哈 具体的场景 不然我无法定位问题 是插件冲突呢 还是插件性能问题呢 还是其他啥的

**Comment by EmptyDreams** [comment]
> 

我在编写 JS 文件的时候，打字和删除文字都有明显的卡顿（包括打字符串内容的时候）。

有关信息：
```
Non-Bundled Plugins:
    com.faebeee.vuecomponentcreator (2.7.3)
    com.intellij.zh (231.283)
    org.jetbrains.settingsRepository (231.8109.91)
    org.jetbrains.plugins.stylus (231.8109.91)
    com.fxiaoke.lizc8407 (2.2.0)
    Statistic (4.2.7)
    com.wix.sasslint (1.1.2)
    Key Promoter X (2023.1.0)
    com.jetbrains.plugins.jade (231.8109.91)
    cn.fjdmy.uniapp (1.0.4)
    tv.twelvetone.intellij.plugins.intellivue (1.1.32)
    com.demonwav.minecraft-dev (2023.1-1.6.4)
    com.chrisrm.idea.MaterialThemeUI (8.6.3)
    cn.yiiguxing.plugin.translate (3.4.2)
    com.mallowigi (90.0.0)
```

如果需要的话，我也可以提供 JFR 记录以及其它诊断数据。

**Comment by lqc520** [comment]
需要提供更多的信息哈 比方说 是否在其他电脑也出现 编写什么内容会出现啥的

**Comment by EmptyDreams** [comment]
> 需要提供更多的信息哈 比方说 是否在其他电脑也出现 编写什么内容会出现啥的

比如说我在 `@/store/index.js` 中键入如下内容：

```
export const piniaStore = defineStore('driver', {
    state: () => {
        return {
            user: {
                login: false,
                name: '',
                id: '',
                statistics: {
                    score: 0,
                    count: 0
                }
            }
        }
    }
})
```

在打的过程中就会有明显卡顿，换行时尤为明显。

同时使用 `Backspace` 删除内容时也会卡，短按长按都会卡，长按 `Backspace` 时只有刚开始会卡一会，然后突然删掉好多东西，如果继续按住的话剩下的内容就会比较顺畅的删除掉。

我尝试关掉了 `Uniapp Tool` 以外的所有非官方插件，但是问题仍然存在，关闭 `Uniapp Tool` 后卡顿消失。

我使用录屏演示了一下效果：https://www.aliyundrive.com/s/qi6UC7dGUyR

视频中多次出现“闪现”出多个文字的情况，就是输入的时候卡顿了。

**Comment by lqc520** [comment]
看了的已安装列表，判断不是插件冲突、看了你的视频、我尝试了一下，无法复现。可以尝试一下清除ide缓存试一下、或者换台电脑看看有没有这个问题，或者新建一个项目 看看有没有这个问题 多重排查一下

**Comment by EmptyDreams** [comment]
> 看了的已安装列表，判断不是插件冲突、看了你的视频、我尝试了一下，无法复现。可以尝试一下清除ide缓存试一下、或者换台电脑看看有没有这个问题，或者新建一个项目 看看有没有这个问题 多重排查一下

我在舍友的电脑上也没有还原出卡顿，清除 IDE 缓存后卡顿消失，我再观察几天看看吧。
