### ISSUE TITLE
1.0.3版本的 不能识别swiper-item 这个源生组件呢~

### ISSUE THREAD

**Issue by xyh-994** [lqc520/uniapp-plugin#14]
![image](https://github.com/lqc520/uniapp-plugin/assets/28472064/2702b870-c95d-42d9-971a-b47c751694f8)
附个图~
![image](https://github.com/lqc520/uniapp-plugin/assets/28472064/601bf48d-d598-457e-b031-c0846e449b97)

**Comment by lqc520** [comment]
是的 这个没加上,下个版本加上 ad你们用的多吗

**Comment by xyh-994** [comment]
少用 
我去下了1.0.4的了~ 刚想关了这个呢

**Comment by xyh-994** [comment]
> 是的 这个没加上,下个版本加上 ad你们用的多吗

用得比较少，
若若的问一句 支持事件提示麻烦嘛。  如@touchstart 这种

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/17bf4b9b-9a10-496f-9f09-9994de36c590)
这个是有的吧

**Comment by xyh-994** [comment]
> ![image](https://user-images.githubusercontent.com/33248612/237602590-17bf4b9b-9a10-496f-9f09-9994de36c590.png) 这个是有的吧


你这个是啥插件呢.
![image](https://github.com/lqc520/uniapp-plugin/assets/28472064/19961fe4-1bae-441c-8798-28e6f32656ac)
我这个直接尬住

**Comment by lqc520** [comment]
你这个是scroll-view 组件 https://uniapp.dcloud.net.cn/component/scroll-view.html 官方这边木有提供这个事件哦

**Comment by lqc520** [comment]
这个内置组件提示是前些天有个老板打赏了一下 希望加强内置组件刚爬取的 我就想不应该出现这个问题

**Comment by xyh-994** [comment]
> 这个内置组件提示是前些天有个老板打赏了一下 希望加强内置组件刚爬取的 我就想不应该出现这个问题



> 你这个是scroll-view 组件 https://uniapp.dcloud.net.cn/component/scroll-view.html 官方这边木有提供这个事件哦

呃 我就随便举个栗子..
![image](https://github.com/lqc520/uniapp-plugin/assets/28472064/49191ce4-3f23-4e4b-811e-81fe8ee17896)

**Comment by xyh-994** [comment]
> 这个内置组件提示是前些天有个老板打赏了一下 希望加强内置组件刚爬取的 我就想不应该出现这个问题

我不理解..
我装的是1.0.4的..

**Comment by lqc520** [comment]
简单呀 你具体说哪个组件 哪个事件没有提示

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/09259ad9-fb94-4501-b1ce-f4e68cf25d30)

**Comment by xyh-994** [comment]
> 你这个的需求 是什么组件需要事件提示 还是所有组件都需要事件提示 提示什么事件呢 我没有看明白



> 

啊.. 就类似你截图的那样就满足了..
不懂我是缺什么别的插件么

**Comment by lqc520** [comment]
？？？ 我截图的这个能力不就是我这个插件提供吗 并且你也没有提供不能提示的图 你的两张图都不对

**Comment by lqc520** [comment]
你自己研究一下怎么用吧 在组件那边打@ 只有内置组件有提供的 都会提示！！！！

**Comment by xyh-994** [comment]
> ？？？ 我截图的这个能力不就是我这个插件提供吗 并且你也没有提供不能提示的图 你的两张图都不对

![image](https://github.com/lqc520/uniapp-plugin/assets/28472064/3ec411e2-017d-469f-b5e6-78e4ee436365)
那可能你那边太严谨了?....
view 我没记错的话 。 。 。似乎这些事件都有。。。 除了scroll 那些不确定以外。。。
这些类似每个组件的基础事件 。。

**Comment by lqc520** [comment]
基础事件因为vue插件已经提供了通用的 我这边没有另外处理哈  我这边只提供官方文档中内置组件中的属性说明中的事件哈

**Comment by lqc520** [comment]
我可能理解错你的意思了

**Comment by xyh-994** [comment]
> 我可能理解错你的意思了

那行吧... 可能是我少装了什么别的插件么..
怎么好像我的那个插件没提示这些基础事件
