### ISSUE TITLE
renderjs能否支持语法高亮和智能提示？

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#16]
<img width="922" alt="uni" src="https://github.com/lqc520/uniapp-plugin/assets/29171233/aaa93e18-4a68-4eb9-8f4c-59717712c20a">

**Comment by lqc520** [comment]
后续版本会考虑支持，目前先支持大众化需求哈。

**Comment by jasonHG** [comment]
好的，感谢。
