### ISSUE TITLE
希望增加UniCloud支持

### ISSUE THREAD

**Issue by changxinjie** [lqc520/uniapp-plugin#17]
希望增加UniCloud支持, 比如:

JQL查询面板
Schema编辑/预览
uniCloud代码补全

**Comment by lqc520** [comment]
后续版本会考虑支持

**Comment by zCanoe** [comment]
非常希望增加对unicloud的支持

**Comment by lqc520** [comment]
uniCloud的补全功能是有的吧 因为我没有用UniCloud开发过 JQL查询面板 Schema编辑/预览 这一块功能是具体描述一下

**Comment by zCanoe** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/43891961/48998abe-3791-44b6-90de-57a5e617a416)
uniCloud 代码补全是有的，想要的是这个，关联uniCloud云空间，并可以下载Db Schema 和云函数，可以开启云函数本地调试。
