### ISSUE TITLE
bug：新建页面后编译报错，查找不到文件

### ISSUE THREAD

**Issue by ipconfigall** [lqc520/uniapp-plugin#18]
步骤：
1：![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/990c56f7-8889-464e-957e-25d816ef2eeb)
2：![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/4dc2ed06-5ee4-4cf4-85ac-6a56b1a1ec75)

**Comment by lqc520** [comment]
#19
