### ISSUE TITLE
bug：新建页面后编译报错，查找不到文件

### ISSUE THREAD

**Issue by ipconfigall** [lqc520/uniapp-plugin#19]
步骤：
1：![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/990c56f7-8889-464e-957e-25d816ef2eeb)
2：![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/4dc2ed06-5ee4-4cf4-85ac-6a56b1a1ec75)

报错内容：
微信小程序报错提示： 编译失败，无法找到编译后的js文件。但是在微信小程序中能找到对应文件
idea: 编译正常

**Comment by lqc520** [comment]
微信ide不支持JSON文件热部署 是否在微信IDe点击了重新编译

**Comment by lqc520** [comment]
主包发行问题 但是发现了一个bug 分包多了root 路径

**Comment by lqc520** [comment]
主包没发现问题 但是发现了一个bug 分包多了root 路径

**Comment by lqc520** [comment]
如果是分包问题 [点我下载](https://github.com/lqc520/uniapp-plugin/releases/tag/v1.0.5.A) 不是的话请提供更多信息哈
