### ISSUE TITLE
条件编译部分能否高亮和可折叠呢？

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#21]
<img width="944" alt="2" src="https://github.com/lqc520/uniapp-plugin/assets/29171233/cf18a20a-99ac-4346-95e9-80d0781e8d6a">

**Comment by jasonHG** [comment]
ok,加油

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.5.B/Uniapp-1.0.5.zip)

**Comment by jasonHG** [comment]
有点问题，第一行可以折叠，后面的不行。
![9](https://github.com/lqc520/uniapp-plugin/assets/29171233/a6c3d58d-5231-49ea-8bbc-3041c4ab0a8f)
可以加下高亮，这样代码可读性更好点，类似这种，感谢🙏。
![10](https://github.com/lqc520/uniapp-plugin/assets/29171233/d7c4b345-168e-4e6c-8512-a357a358ef92)

**Comment by lqc520** [comment]
不行的原因是我这边识别的是// # 你那边空格没了哈 默认提示对都会带空格 高亮没问题下个版本上哈 因为近期比较忙😁

**Comment by jasonHG** [comment]
> 不行的原因是我这边识别的是// # 你那边空格没了哈 默认提示对都会带空格 高亮没问题下个版本上哈 因为近期比较忙😁

好的，了解。
