### ISSUE TITLE
启动后，IDEA变卡，码字有延迟

### ISSUE THREAD

**Issue by spinachomes** [lqc520/uniapp-plugin#22]
我的是M1 PRO，不知道是不是MAC的原因？

**Comment by lqc520** [comment]
1、清楚ide缓存尝试一下
2、换webstorm 尝试一下
3、看一下其他的电脑是否能复现这个问题

**Comment by lqc520** [comment]
理论上不应该 我们这边都是正常的 不卡顿 但是确实有个别人人出现这个问题 目前无法定位是谁的问题 并且他在室友的电脑无法复现 最终他的清理了IDE缓存 变正常
