### ISSUE TITLE
Mac生命周期不提示+希望支持.test生成<view class="test"></view>

### ISSUE THREAD

**Issue by S27149** [lqc520/uniapp-plugin#23]
Mac电脑下，onShow等等的生命周期函数不会提示；希望在这个插件辨别当前项目是uniapp项目的时候，，使用快捷键键入：.test + tab按键默认生成的是`<view class="text"></view>`标签，而不是`<div class="text"></div>`标签

**Comment by lqc520** [comment]
生命周期函数提示没问题，第二点得研究一下哈

**Comment by S27149** [comment]
还有一个问题就是在mac电脑上使用uni不提示了，直接显示方法不存在
![image](https://github.com/lqc520/uniapp-plugin/assets/72686391/0828182e-f8c8-4926-988d-5fc2d018fa40)

**Comment by lqc520** [comment]
hx呢 还是cli  vue2呢还是 vue3

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/68d6d041-93f1-4c78-b3af-bf4617ec0846)
我这边测试了 cli和非cli都正常 cli项目走的是node_model里面的types hx项目走的是插件内置的types

**Comment by S27149** [comment]
我这个项目是用hx创建的，然后用webstorm打开的

**Comment by S27149** [comment]
你建议的我已经全部重新试过了

**Comment by S27149** [comment]
还是老样子，就差重装websorm

**Comment by lqc520** [comment]
ws 什么版本的

**Comment by lqc520** [comment]
因为ide 偶尔会出现索引问题 所以需要清理缓存 我晚上有空的话用黑苹果看看 win没办法复现

**Comment by S27149** [comment]
我找到原因了，删除那个项目下的.idea文件就可以了

**Comment by lqc520** [comment]
那就好 生命周期提示是已经开发完了 这周看一下会发布一个版本 我这边就先关闭这个issues了

**Comment by S27149** [comment]
好的👌

**Comment by lqc520** [comment]
.test生成<view class="test"></view> 以支持

**Comment by S27149** [comment]
谢谢大佬
