### ISSUE TITLE
可以支持一下2022.3.x吗

### ISSUE THREAD

**Issue by lun3322** [lqc520/uniapp-plugin#24]
😊😊😊

**Comment by lqc520** [comment]
可以是可以啦，因为老版本ide用uniapp-support 也是免费的啦，所以没有发布对老ide支持的插件

**Comment by lqc520** [comment]
[已支持 点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.7-223.1/Uniapp-1.0.7-223.1.zip) 有啥问题及时反馈
