### ISSUE TITLE
希望可以支持编译时压缩代码

### ISSUE THREAD

**Issue by ipconfigall** [lqc520/uniapp-plugin#25]
目前的运行模式下，编译微信小程序不会自动压缩代码，只能在manifest.json中设置，如下：
![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/db011288-1854-44bc-9983-ea096ecb56a3)
是否可以在不改变配置文件的前提下，进行代码压缩？

**Comment by lqc520** [comment]
可以的呀 下个版本发布 编译的时候加个参数就行 我是考虑不是发行的话没必要弄
