### ISSUE TITLE
怎么支持环境变量

### ISSUE THREAD

**Issue by ajiader** [lqc520/uniapp-plugin#26]
![image](https://github.com/lqc520/uniapp-plugin/assets/4979798/e3e4d055-36d1-448d-9ba1-63c2fd7e1a27)
类似这种怎么通过webstrom实现开发环境和生产环境

**Comment by lqc520** [comment]
你的需求是啥

**Comment by ajiader** [comment]
https://blog.csdn.net/weixin_43743175/article/details/129714696  就是这个看能实现不

**Comment by lqc520** [comment]
不支持
