### ISSUE TITLE
能否支持uni-ui的智能提示

### ISSUE THREAD

**Issue by E-10000** [lqc520/uniapp-plugin#29]
就是官网的[这个](https://uniapp.dcloud.net.cn/component/uniui/uni-ui.html)，uni-ui
原生的有了，但是还是更希望支持这个uni-ui呢，毕竟是官方的UI工具。每次写的时候都没有提示还有波浪号好难受。
![image](https://github.com/lqc520/uniapp-plugin/assets/52124130/6f045199-3cfe-4f40-846a-ce1a5a303602)

**Comment by lqc520** [comment]
理论上uni-ui符合easy-com规范 不会出现这个 你这个是hx项目 还是cli 项目 vue几 是npm的 还是 导入的

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/85c6f375-de66-45aa-b74b-a53802e21e35)

**Comment by E-10000** [comment]
> 理论上uni-ui符合easy-com规范不会出现这个你这个是hx项目还是cli项目vue几是npm的还是导入的

cli项目，vue3.2.45，用IDEA写的。npm导入，node v14.21.3 ，npm 6.14.18。
但是目前项目已经是按照[文档](https://uniapp.dcloud.net.cn/component/uniui/quickstart.html#npm%E5%AE%89%E8%A3%85)  导入easycom了，写是可以写，使用也没问题，就是IDEA显示识别不了
```json
	"easycom": {
		"autoscan": true,
		"custom": {
			// uni-ui 规则如下配置
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	}
```

**Comment by lqc520** [comment]
经过测试 npm 导入的是有这个问题 正常的npm导入不需要插件特别处理 比方说uview ide会自动识别 但是uni-ui估计是官方没处理 可以https://ext.dcloud.net.cn/plugin?id=55 先通过这种形式导入 会识别 后续我靠一下兼容npm的uni-ui识别

**Comment by E-10000** [comment]
> 经过测试 npm 导入的是有这个问题 正常的npm导入不需要插件特别处理 比方说uview ide会自动识别 但是uni-ui估计是官方没处理 可以https://ext.dcloud.net.cn/plugin?id=55 先通过这种形式导入 会识别 后续我靠一下兼容npm的uni-ui识别

好的，谢谢大佬~~~start啦~~
