### ISSUE TITLE
插件是真的好用，但是我是不是配置有问题。。 启用插件后打代码很卡

### ISSUE THREAD

**Issue by xyh-994** [lqc520/uniapp-plugin#3]
电脑本身32G i7 8750H 
idea 放在固态硬盘里

启用插件之后打字的时候按一个字母得等一秒..才能出来.....巨难受.. 有没有办法呢..
是我哪里操作不对么 

麻烦大佬了!

**Comment by lqc520** [comment]
您的联系方式是多少 我远程看看

**Comment by lqc520** [comment]
不知道是否和其他插件冲突了还是啥 能否提供更多信息 禁用此插件后是否就不卡了?

**Comment by xyh-994** [comment]
> 不知道是否和其他插件冲突了还是啥 能否提供更多信息 禁用此插件后是否就不卡了?
呃对的，禁用了就不卡了。。
有可能是因为我用idea吧。  后来换webstorm 就不卡了。。

**Comment by xyh-994** [comment]
问题也不大 可能是我idea插件装了不少导致的..

**Comment by lqc520** [comment]
如果还出现这个问题 再来联系我
