### ISSUE TITLE
idea 下码字特别卡 只好先关了

### ISSUE THREAD

**Issue by ImKujio** [lqc520/uniapp-plugin#30]
设备信息：
* CPU：i7 6700
* MEM：32
* OS：Windows10

软件信息：
* 版本： 2023.1.2U
* JVM设置：-Xms6G，-Xmx6G，-Xmn2G
* 安装的其他第三方前端插件：IntelliVue

项目信息：
* 初始化工具：cli
* Vue版本：3.3.4
* Vite版本：4.3.9

组件使用HBuilderX单个导入(非整个uni-ui全部组件)，没有组件时不卡，六七个组件时就开始卡了，如下。

![image](https://github.com/lqc520/uniapp-plugin/assets/18486297/55dc5c47-b916-492e-bf33-cfc95b79fd2b)

**Comment by lqc520** [comment]
兄弟可以 6700的机子还能跑 CPU不会动不动百分百吗 可以尝试删除项目下的.idea文件 看看还不会不会

**Comment by ImKujio** [comment]
> 兄弟可以 6700的机子还能跑 CPU不会动不动百分百吗 可以尝试删除项目下的.idea文件 看看还不会不会

删了.idea还是不行，ps：这配置我也没办法

**Comment by lqc520** [comment]
那目前没有办法啦，你可能更适合老版本IDE 新IDE比较吃资源

**Comment by ImKujio** [comment]
大佬您的插件也不支持老版本啊，今天下班了，明天再研究研究
