### ISSUE TITLE
关于路径识别问题

### ISSUE THREAD

**Issue by tianma8023** [lqc520/uniapp-plugin#32]
Uniapp-Tool 插件版本: 1.0.5
IntelliJ Idea 版本: 2023.1.3 - Build #IU-231.9161.38, built on June 20, 2023

在项目根目录下定义的路径别名:
```js
// 引入path模块
const path = require("path");

function resolve(dir) {
	return path.join(__dirname, dir);
}

module.exports = {
  configureWebpack: {
    resolve: {
      "@": resolve("src"),
      "@libs": resolve("src/libs")
      "@p_c": resolve("src/pages/components")
    }
  }
}
```

项目文件的目录结构如下
```
├── src
│   ├── libs
│   │   └── utils.js
│   └── pages
│       └── components
│           └── my-component.vue
└── vue.config.js
```

在实际使用过程中，发现使用路径别名引入的组件或者库没办法点击跳转到对应文件:
```vue
<script>
//  @libs 的路径别名，无法识别，改成  "@/libs/utils" 才能识别
import {rpx2px} from "@libs/utils"
// @p_c 的路径别名无法识别，改成 "@/p_c/my-component.vue" 才能识别 
import MyComponent from "@p_c/my-component.vue"
<script/>
```

但实际上，如果不安装此 `Uniapp-Tool` 插件，intellij idea 默认引入组件的时候，都是 "@lib/xxx", "@p_c/yyy" 的形式，而不是 "@/libs", "@/p_c" 的形式。这样就会导致，安装本插件后，很多旧页面的组件等都没办法点击跳转了。

麻烦看下这个问题该如何解决。

**Comment by lqc520** [comment]
这个是这样子的 因为hx创建uniapp项目 idea默认不能识别到@路径 所以插件做了@路径识别为基础路径 你如果是cli创建的项目可以尝试一下 idea本身是否识别你的配置

**Comment by tianma8023** [comment]
项目本身是用 cli 创建的，idea 本身也能识别 vue.config.js 下配置的路径别名。不过他识别的是 "@xx/" 这种格式的，而本插件导入进来的是 "@/xx" 这种格式的，导致没办法点进去看代码。

**Comment by lqc520** [comment]
意思是禁用插件可以识别到对吗

**Comment by lqc520** [comment]
如果是的话 下个版本 我去除对cli项目的路径识别

**Comment by tianma8023** [comment]
是的，禁用本插件就能正确识别路径。

**Comment by tianma8023** [comment]
好的，那麻烦你再迭代下插件，辛苦辛苦~

**Comment by lqc520** [comment]
了解

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.6.A/Uniapp-1.0.6.zip) 试一下  有问题及时反馈

**Comment by tianma8023** [comment]
@lqc520 刚刚试了下，没啥问题，跳转都正常了。感谢感谢。
