### ISSUE TITLE
com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by YanXinDong** [lqc520/uniapp-plugin#33]
com.google.gson.stream.MalformedJsonException Use JsonReader.setLenient(true) to accept malformed JSON at line 125 column 2 path $
<img width="675" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/39759322/5ee5ffef-479a-466b-9054-05deb55c57da">
大佬，我运行报这个错是为啥啊？

**Comment by lqc520** [comment]
看上去是json解析出错 因为要判断是vue几项目 要解析manifest.json 文件 你看看125行 第三列是啥数据

**Comment by YanXinDong** [comment]
<img width="712" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/39759322/dda46ce4-8542-4e49-b2dc-6d606e94e795">
好了，谢谢大佬，最后几行有同事加的注释，删了就行了
