### ISSUE TITLE
关于 uniapp API 文档跳转位置的问题

### ISSUE THREAD

**Issue by tianma8023** [lqc520/uniapp-plugin#34]
不好意思又来提issue了

我发现在 windows 上, v1.0.6 和 v1.0.5 有一些差别。

比如这段代码:
```javascript
uni.chooseImage()
```
点击 `chooseImage` 进行跳转的时候，期望看到这个 uniapp 的 API 的文档。

在 v1.0.5 上，会跳转进 `${project}/node_modules/@dcloudio/types/uni-app/uni.d.ts` 文件中，从而能看到这个API的相关文档：
<img width="572" alt="20230713170923" src="https://github.com/lqc520/uniapp-plugin/assets/7833704/768362d1-07ea-4d12-a7f7-c7c658bdd4e5">
此时，此API的参数 `UniNamespace.ChooseImageOptions` 能点击跳转查看相关文档。

但在 v1.0.6 上点击跳转进入的是插件自带的 `instrumented-uniapp-1.0.6.jar` 中的文件：
`C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\Uniapp\lib\instrumented-uniapp-1.0.6.jar!\library\uniapp\uni-app\uni-patches\promisify\uni.d.ts`
<img width="731" alt="20230713171426" src="https://github.com/lqc520/uniapp-plugin/assets/7833704/a93d5882-5ea9-4e5a-9cba-fcc8b90518c7">

同时，此API的参数 `UniNamespace.ChooseImageOptions` 也没办法点击跳转。

这个问题的出现，会不会跟v1.0.6解决的相对路径的识别有关系？

**Comment by lqc520** [comment]
[下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.6.A/Uniapp-1.0.6.zip) 试试

**Comment by tianma8023** [comment]
ok，目前用起来没问题了 @lqc520
