### ISSUE TITLE
webstorm2023.1.4运行失败

### ISSUE THREAD

**Issue by shaojiaqi08** [lqc520/uniapp-plugin#36]
pc操作系统：windows
HBuilderX类型：最新正式版
项目类型：vue2/uniapp

报错原因：
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 104 column 2 path 

![Snipaste_2023-07-21_14-30-08](https://github.com/lqc520/uniapp-plugin/assets/50544906/3e7141e4-49ea-47ed-b9ff-134ed5813ff2)

![Snipaste_2023-07-21_14-37-31](https://github.com/lqc520/uniapp-plugin/assets/50544906/8ca2d50a-83da-44c0-98b5-2aa8aee966d1)

**Comment by lqc520** [comment]
因为需要解析判断是vue几项目 随意需要读取JSON文件 您这边的JSON文件有非JSON格式的数据 更具提示刚改就好

**Comment by lqc520** [comment]
可以看 33 issued

**Comment by lqc520** [comment]
#33

**Comment by shaojiaqi08** [comment]
有注释，删掉可以了
