### ISSUE TITLE
webstorm2023.1.4插件报错

### ISSUE THREAD

**Issue by shaojiaqi08** [lqc520/uniapp-plugin#37]
pc操作系统：windows
HBuilderX类型：最新正式版
项目类型：vue2/uniapp

新建的项目，编辑器打开一直报错

![Snipaste_2023-07-21_17-49-05](https://github.com/lqc520/uniapp-plugin/assets/50544906/16d4ec15-7b45-40b0-a43d-1e37006c05ae)

**Comment by lqc520** [comment]
hx项目还是 cli项目

**Comment by lqc520** [comment]
可以下载1.0.6看看有没有这个问题

**Comment by shaojiaqi08** [comment]
> hx项目还是 cli项目

hx项目，目前更新到1.0.6版本也是一样的报错问题

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/122e50c4-1413-4ea6-bf98-decf426359b5)
hx创建vue2项目 目前我这边测试没问题 刚创建的项目

**Comment by lqc520** [comment]
无法复现 我这边重新安装了插件也无法复现问题 您这边可以尝试 第一 删除项目下的 .idea 第二重新安装插件 也可以尝试卸载安装

**Comment by shaojiaqi08** [comment]
> 无法复现 我这边重新安装了插件也无法复现问题 您这边可以尝试 第一 删除项目下的 .idea 第二重新安装插件 也可以尝试卸载安装
创建项目试下用其他模板，我是在uniapp中创建了这个模板，在idea打开就会出现这个错误
![Snipaste_2023-07-24_10-09-18](https://github.com/lqc520/uniapp-plugin/assets/50544906/3d83b65f-46b0-450a-8903-e38feea182bc)

**Comment by shaojiaqi08** [comment]
> 无法复现 我这边重新安装了插件也无法复现问题 您这边可以尝试 第一 删除项目下的 .idea 第二重新安装插件 也可以尝试卸载安装

创建项目试下用其他模板，我是在uniapp中创建了这个模板，在idea打开就会出现这个错误
![Snipaste_2023-07-24_10-09-18](https://github.com/lqc520/uniapp-plugin/assets/50544906/f57c9088-0f83-40d1-853b-6c6b3fcfcdd2)

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/5304e5f2-12a9-4017-b5cc-de5b62564f0b)
正常的呢  你这边可以用其他电脑安装这个插件试一下 或者同事的电脑 目前这个版本下载了已经二千多人次 没人反馈这个问题呢 我们自用也没用问题呢 我开发这个插件主要是为了公司自用

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/94182bd4-e71a-4c4f-bfa8-35d597d894c6)

**Comment by lqc520** [comment]
我建议您这边清除ide 缓存 如果还出现问题 报错提供给我 我这边复现您的步骤

**Comment by lqc520** [comment]
现在无法确认是ide问题 还是插件问题 目前就您反馈了这个问题

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/3696bfb8-9b04-47d8-a02a-bfe13e9eb2e4)
我这边是感觉您这个vue文件有问题

**Comment by lqc520** [comment]
其他项目尝试一下 有问题继续反馈

**Comment by shaojiaqi08** [comment]
> ![image](https://user-images.githubusercontent.com/33248612/255454376-5304e5f2-12a9-4017-b5cc-de5b62564f0b.png) 正常的呢 你这边可以用其他电脑安装这个插件试一下 或者同事的电脑 目前这个版本下载了已经二千多人次 没人反馈这个问题呢 我们自用也没用问题呢 我开发这个插件主要是为了公司自用

目前我这边的话，打开.vue文件就会出现这个问题，这个问题主要应该是影响了idea vue代码高亮的问题，运行的确是没有什么问题的

**Comment by shaojiaqi08** [comment]
这个问题暂时是不影响运行，只是我已打开.vue文件就会提示，而且这个好像也会影响到vue代码块的代码高亮
![image](https://github.com/lqc520/uniapp-plugin/assets/50544906/2c447389-9907-46c0-9c12-9179ff2312c6)

**Comment by lqc520** [comment]
肯定的 你这边创建一个正常vue文件结果 把你的数据复制进去就行 你这个结构不对 导致的

**Comment by lqc520** [comment]
??

**Comment by shaojiaqi08** [comment]
> 肯定的 你这边创建一个正常vue文件结果 把你的数据复制进去就行 你这个结构不对 导致的

发现了根目录只要有uni_modules或者node_modules，ide就有这个报错，并不是vue文件的问题

**Comment by lqc520** [comment]
嗯 我们的项目没有这个问题 你可以安装其他插件使用试试 比如uniapp support
