### ISSUE TITLE
求助！！！显示 Please specify working directory correctly 错误

### ISSUE THREAD

**Issue by guoliangmaa** [lqc520/uniapp-plugin#38]
求助！MacOS13.5 在配置后显示  Please specify working directory correctly 错误。

<img width="1040" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/50517323/d5ca22bf-f3e6-46ff-b167-f15beb5048f6">
<img width="982" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/50517323/d909ff91-bc76-42e5-ac39-659bbbbf3bed">

**Comment by guoliangmaa** [comment]
我更改hbuilderx 安装路径也会出同样的问题

**Comment by lqc520** [comment]
你是不是安装了两个插件 uniapp tool 插件在 tools里面配置

**Comment by lqc520** [comment]
Tools - > Uniapp
