### ISSUE TITLE
【优化建议】自动生成生命周期时的输入指针与样式格式化应该调整

### ISSUE THREAD

**Issue by T-miracle** [lqc520/uniapp-plugin#39]
![图片](https://github.com/lqc520/uniapp-plugin/assets/44044121/ae0ddad0-274b-4a86-b630-df536ceb0ca4)
1. 指针默认应该是括号内，而不是外面
2. 样式应该进行自动格式化

**Comment by lqc520** [comment]
光标位置在内部是问题不大 有两三个生命周期函数做了这个处理 格式化 问题不大 是考虑到有个别人不喜欢格式化 下个版本优化

**Comment by lqc520** [comment]
带参路径识别这个也下个版本发布 感谢老板的赞赏 ❤️

**Comment by lqc520** [comment]
[测试看看](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.7-231.1/Uniapp-1.0.7-231.1.zip)

**Comment by T-miracle** [comment]
> [测试看看](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.7-231.1/Uniapp-1.0.7-231.1.zip)

### 测试环境

Windows 11

### 测试软件

- JetBrian IDEA 2022.2.3
- JetBrian IDEA 2023.1.3

### 测试结果

1. 带参跳转无问题
2. 现在生成周期函数括号默认不换行，输入指针在闭合大括号中（个人感觉还成）
3. JetBrian IDEA 2022.2.3 无法安装

**Comment by lqc520** [comment]
2、换行是可以,也能获取到系统设置的缩进 但是光标位置不太理想 第二行直接在顶部了 所以还是采取默认不换行了 
3、因为官方223版本的api和231的不同  所以不支持223 要支持223得单独编译一个版本呢

**Comment by lqc520** [comment]
3、已支持 [223版本安装](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.7-223.1/Uniapp-1.0.7-223.1.zip) 你要是有用老版本 可以试试 没啥大问题 我发布到插件市场去

**Comment by T-miracle** [comment]
> 3、已支持 [223版本安装](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.7-223.1/Uniapp-1.0.7-223.1.zip) 你要是有用老版本 可以试试 没啥大问题 我发布到插件市场去

![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/e03103c6-df10-4e4b-b96b-6bc26bfacf65)
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/6876ba73-173a-45d9-b0fb-efb1551dbc40)

目前我的这个2022.2.3版本用不了，问题也不大，平常也是用最新版本

**Comment by lqc520** [comment]
你这个是222版本 这个我已经发布了 你可以直接在插件市场安装哈
