### ISSUE TITLE
作者大大,多久可以实现ios 安卓真机运行呀

### ISSUE THREAD

**Issue by du6688** [lqc520/uniapp-plugin#4]
作者大大,多久可以实现ios 安卓真机运行呀

**Comment by lqc520** [comment]
等我有空的时候 研究一下hx是怎么运行的

**Comment by du6688** [comment]
作者大大,可以添加一个在pages文件夹 右键添加uniapp 页面 自动写入到pages.json文件里面

**Comment by lqc520** [comment]
这个问题不大 下个版本发布

**Comment by du6688** [comment]
还有就是 uni.navigateTo点击跳转或者其他跳转 到页面的时候 按住ctrl 点击跳转路径可以跳转到对应的代码界面

**Comment by du6688** [comment]
在pages文件里面点击path 都不能跳转到对应界面

**Comment by lqc520** [comment]
小问题 下个版本一起发布

**Comment by lqc520** [comment]
安卓的下个版本再发布 [点我下载](https://github.com/lqc520/uniapp-plugin/releases/tag/v1.0.3.A) 先发布一个小版本 功能慢慢完善
