### ISSUE TITLE
新版本webstorm的vuex文件全部红色的

### ISSUE THREAD

**Issue by du6688** [lqc520/uniapp-plugin#40]
<img width="829" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/52399314/978d66b9-65ba-45b2-adbc-f83bbcc911f4">

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/a974a0c8-5db7-4a07-9bc6-2ee697d08e86)
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/e161d74b-ce6e-486a-98a5-c863dd7ee9c3)
没发现这个问题 可以尝试清楚ide 缓存 删除.idea 文件试试 或者提供更多信息
