### ISSUE TITLE
带参数的url无法ctrl+点击跳转

### ISSUE THREAD

**Issue by BugGeeker** [lqc520/uniapp-plugin#41]
![image](https://github.com/lqc520/uniapp-plugin/assets/35688923/e775f6d3-9628-4a4c-bbef-8bcc82f1cbc6)

**Comment by lqc520** [comment]
1.0.6版本吗

**Comment by BugGeeker** [comment]
是的
![image](https://github.com/lqc520/uniapp-plugin/assets/35688923/1187ac25-7493-4647-be1e-4eb1086c2d5b)

**Comment by lqc520** [comment]
#39 新版本已经优化 这几天会发布

**Comment by lqc520** [comment]
你也快有自行下载1.0.7-231.2 版本哈
