### ISSUE TITLE
rpx，upx单位格式化在css文件中失效，在vue文件中有效？

### ISSUE THREAD

**Issue by vacuole1989** [lqc520/uniapp-plugin#42]
作者你好，最近在插件使用过程中发现一个问题，就是uniapp项目下面，我发现rpx和upx单位在css文件中的话使用格式化的时候还是会被加上空格，但是如果在vue文件中的话就没有这个问题。
我这边在多种情况下（删除缓存，删除.idea，重新创建项目等）测试都发现有上面的问题。
这个是否可以可以劳烦修复一下？

**Comment by lqc520** [comment]
![fab4d4175994044a0d18bd8d4cb1c3c](https://github.com/lqc520/uniapp-plugin/assets/33248612/5dd82a05-ab83-460c-9678-88efe6d375cb)

经测试 没有您反馈的问题

**Comment by lqc520** [comment]
估计还是您环境的问题 你ide版本 插件版本是多少

**Comment by vacuole1989** [comment]
IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023


Uniapp Tool   1.0.7-231.2

**Comment by vacuole1989** [comment]
刚刚测试了很多次，大概测试出来什么情况下会出现问题：
1、第一步：由于我用的是IDEA，我一般都是新建一个空的Project，然后uniapp的项目都是通过Mudule方式导入进来的，软件打开之后进行格式化都会出现空格。（感觉是Uniapp Tool插件没有识别到Project的类型所以还没有激活）
2、第二步：然后我直接通过Project的方式打开我的uniapp项目，这个时候格式化不会出现空格。（猜测是这个时候插件检测到项目类型就已经激活了）
3、第三步：然后我再回到之前那个通过Module导入的项目尝试格式化，发现不再出现空格了。（猜测是第二步插件已经激活了，所以当前打开的所有IDEA进行的插件都已经激活，所以格式化就没问题了）
4、刚刚特地下载了一个WebStorm看了一下，发现这个软件并不像IDEA一样，WebStorm只有Project一种模式，没有Module的这种模式，所以WebStorm不会出现上述问题。

**Comment by lqc520** [comment]
对 目前插件不支持子模块模式  看一下下个版本 支持一下新建uniapp项目 就不会出现您这个问题

**Comment by vacuole1989** [comment]
好的，知道了，谢谢
