### ISSUE TITLE
怎么进行分包？

### ISSUE THREAD

**Issue by mhxy13867806343** [lqc520/uniapp-plugin#43]
<img width="542" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/4418166/1dc475fc-80ab-4cf3-912b-92fe65367a7f">
没有可以选择分包操作？

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/ce7b2b19-ac3f-4619-a09e-706ec41af582)

**Comment by lqc520** [comment]
这边是识别page.json的呢 需要自行添加分包root

**Comment by mhxy13867806343** [comment]
能否加个菜单，选择 分包的时候，

**Comment by lqc520** [comment]
啥菜单

**Comment by mhxy13867806343** [comment]
<img width="185" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/4418166/696fbcb4-fbbd-48ff-9252-e44c2ab38fa1">
tfrc选择分包选项的时候，旁边给个输入框，可以输入分包的名字，比如xxxroot,然后在page.json中，和pages同级出现分包的东西了

**Comment by lqc520** [comment]
这一块呢是参考hbx的 hbx那边也是在pages.json那边注册后才会显示分包路径 关于自动注册首次分包结构这一块后续版本会考虑更新 我这边会评估一下 看下通过哪种形式实现比较好
