### ISSUE TITLE
请问mac的路径配置怎么填

### ISSUE THREAD

**Issue by supjairo** [lqc520/uniapp-plugin#46]
找到cli和提示的目录后依然显示路径错误

**Comment by lqc520** [comment]
无效提问 不清楚您配置的路径

**Comment by lqc520** [comment]
并且要带图哦 之前就有一个issure 配置了其他插件 启动了我的插件==

**Comment by lqc520** [comment]
也是一个mac用户 #38

**Comment by supjairo** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/110955894/0be9fabf-89f7-46f7-890b-de81deb736bc)
启动的时候报错不能拉起微信开发者工具
