### ISSUE TITLE
每保存一次 就会被弹起小程序开发界面

### ISSUE THREAD

**Issue by yaoyaochil** [lqc520/uniapp-plugin#48]
希望可以将每次保存就弹起开发工具的动作稍微修改一下 ，可能目前插件的运行逻辑是没保存一次编译之后会有一个执行打开的动作，其实可以取消掉的，编译的文件 小程序开发工具会自动识别的

**Comment by lqc520** [comment]
逻辑已经优化 下个版本近期会发布
