### ISSUE TITLE
scss换行bug

### ISSUE THREAD

**Issue by michael51** [lqc520/uniapp-plugin#5]
有个Bug，安装插件后，style使用scss，敲击回车换行，光标自动排在了最前面，这个不正常。

**Comment by lqc520** [comment]
兄弟 没明白你的意思 本插件scss目前只做了rpx的支持 未做其他改动 如需自定义scss格式 在设置搜索scss可以调整 获取请提供更多的信息

**Comment by michael51** [comment]
用那个收费的插件，位置就是对的。用的你这个插件，这个光标位置就会出问题。昨天排查了很久。
![image](https://user-images.githubusercontent.com/31838439/235038975-5c94fd00-1a9c-420a-b1e7-c14330027ff4.png)

**Comment by michael51** [comment]
补充，只有在scss模式下有这个问题，less和sass都正常

**Comment by lqc520** [comment]
![image](https://user-images.githubusercontent.com/33248612/235039455-3a9c3809-5d09-45f6-8f0c-a9b4ba0a7132.png)
我这边尝试了一下 没有出现你这种情况

**Comment by lqc520** [comment]
![image](https://user-images.githubusercontent.com/33248612/235039708-9dffe4f7-12d0-4128-a7f7-3c7328396954.png)

**Comment by lqc520** [comment]
可以尝试通过禁用插件 排除一下 是冲突还是插件问题 还是啥的

**Comment by michael51** [comment]
> 就是禁用了这个插件就正常，所以我才得出的这个结论。我用的是最新版本的webstrom，不知道是不是有地方冲突。
![image](https://user-images.githubusercontent.com/31838439/235039940-7c4a3ae0-1a23-4f0c-ade5-9fee2f4ca90b.png)

**Comment by michael51** [comment]
你有没有QQ群之内的，实在不行，只有看看其它人的使用情况。

**Comment by lqc520** [comment]
已经确定bug [点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.3/Uniapp-1.0.3.zip)  这边有些新功能还未开发好 如果解决了你的问题 麻烦 [处理一下你的评价](https://plugins.jetbrains.com/plugin/21470-uniapp-tool/reviews)

**Comment by michael51** [comment]
> 已经确定bug [点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.3/Uniapp-1.0.3.zip) 这边有些新功能还未开发好 如果解决了你的问题 麻烦 [处理一下你的评价](https://plugins.jetbrains.com/plugin/21470-uniapp-tool/reviews)
好的，新版本，测试正常了。

**Comment by AkenClub** [comment]
原来是这个插件问题。。我也找了好久，之后不知道是不是哪次重启然后更新了插件就没出现，还以为是 webstorm 的问题

**Comment by michael51** [comment]
> 
哈哈，我也花了不少时间

**Comment by michael51** [comment]
> 原来是这个插件问题。。我也找了好久，之后不知道是不是哪次重启然后更新了插件就没出现，还以为是 webstorm 的问题

哈哈，我也花了不少时间
