### ISSUE TITLE
Webstorm 2023.2.1版本，每次新建一个页面，都会显示uni模块未找到，但是能用，重启webstorm即可

### ISSUE THREAD

**Issue by wepn13232** [lqc520/uniapp-plugin#50]
请问一下这是为什么呢，是因为新版本webstorm的问题吗？
目前的开发环境vue3+ts+vite+uniapp。每次新建一个新的页面，就会报 Vue cannot find module : uni，但是能用，只是爆红而已。重启一下webstorm即可

**Comment by lqc520** [comment]
**描述错误**
对bug的简明描述.

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: x.x.x 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 202x.x.x 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by lqc520** [comment]
请按模板提问哦

**Comment by lqc520** [comment]
减少沟通成本 我不知道您用的插件版本是多少

**Comment by lqc520** [comment]
重新提一个issues 我这边复现一下

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/c9a7637c-5656-4141-b186-4c103bdfcd4d)
我这边测试没啥问题
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/9a5342b4-6e38-4302-9138-ff53c36b9202)
