### ISSUE TITLE
Webstorm 2023.2.1版本，每次新建一个页面，都会显示uni模块未找到，但是能用，重启webstorm即可

### ISSUE THREAD

**Issue by wepn13232** [lqc520/uniapp-plugin#51]
**描述错误**
Webstorm 2023.2.1版本，每次新建一个页面，都会显示uni模块未找到，但是能用，重启webstorm即可。
新建一页uniapp页面的时候，在这个vue组件里面会提示uni模块不可用。

还请添加显示问题的屏幕截图.
![image](https://github.com/lqc520/uniapp-plugin/assets/29097412/2e63d1f5-93ac-4b05-b69f-924b3b631fd9)

**使用的插件版本**
Uniapp Tool: 1.0.7-231.2
vue: 3
project: vue-cli4 / vue3 / ts / vite / uniapp
ide: WebStorm 2023.2.1

**环境**
提供更多的信息:
比如:  macOS 11.7.4
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
1、在pages中右键，新建页面（uniapp-tool自带的新建页面操作）
![image](https://github.com/lqc520/uniapp-plugin/assets/29097412/e70cd910-5709-4f65-aab7-c7b608a2d0f1)
2、在页面中使用ts、setup语法糖
3、创建一个func，在里面使用uni.navigateto，就会报错

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by wepn13232** [comment]
抱歉刚刚没有按照模板进行提问

**Comment by wepn13232** [comment]
"vue": "^3.2.45",
"typescript": "~5.1.6",
"vite": "4.4.7",

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/56ade729-4fa2-453b-a5eb-a1703389ecf0)
我这边看是正常的

**Comment by lqc520** [comment]
cli项目提示用的是node_modules 里面@dcloud 自带的type 和插件没关系 hbx项目才是用插件内置的uniapp库

**Comment by lqc520** [comment]
把项目.idea 删除试试 不行就清理缓存 有可能是ide抽风了

**Comment by lqc520** [comment]
[1.0.8插件](https://plugins.jetbrains.com/plugin/21470-uniapp-tool/versions/stable/389966) 这个是新版插件 也可以安装新版的试试 jetbrains还在审核中

**Comment by wepn13232** [comment]
好的好的，我等ide的新版插件更新之后试一下，确实有可能是ide抽风了。顺带问一下上面vue、ts和vite的版本你这边是多少呢？

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/e5a866bf-0313-4496-b82c-121756d54277)

**Comment by lqc520** [comment]
就你这个问题 和这些都没有关系 和这些版本都没有关系 和ide 插件 以及dcloud 的type 有关系

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/0978bf1c-5edb-4dd8-b353-a86ff86c9f0b)

**Comment by lqc520** [comment]
cli 项目是这边引用

**Comment by wepn13232** [comment]
好的好的，谢谢。应该是ide抽风了，因为有时候连导入组件也是识别不到，也得重启ide。

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/50247f7c-e93b-4c2c-bf83-5cd4417bec8d)
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/753a002a-87db-4a62-b370-e5da986c9137)
你那边应该经过这两个步骤就行 先试试2 不行在试试1
