### ISSUE TITLE
vue2项目别名失效

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#55]
**描述错误**
<img width="878" alt="别名1" src="https://github.com/lqc520/uniapp-plugin/assets/29171233/c033954e-8ada-4783-a8ef-50cd2e71da31">

对bug的简明描述.

启用插件之后，之前的vue2的项目（不是uniapp项目，就是纯vue项目）的别名就会失效 ，禁用插件就好了。就是启用之后点击cmd+鼠标左键现在没法点到组件里面去了。

**使用的插件版本**
Uniapp Tool: 1.0.8-231.4
vue: 2
project: vue-cli3
ide: WebStorm 2023.2.1 

**环境**
macOS

**预期行为**
别名有效，cmd+鼠标左键能直接跳到组件中去

**Comment by lqc520** [comment]
感谢反馈 有这个问题 已修复

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.8-231.5/Uniapp-1.0.8-231.5.zip)

**Comment by jasonHG** [comment]
> [点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.8-231.5/Uniapp-1.0.8-231.5.zip)

已经好了，感谢！
