### ISSUE TITLE
uniapp css 默认按Tab生成样式的单位设置为rpx

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#57]
**是关于什么的?**
如下图所示，我希望按Tab生成的单位是5rpx而不是5px。
![CleanShot 2023-09-13 at 14 13 09](https://github.com/lqc520/uniapp-plugin/assets/29171233/2e0613b2-d471-44f5-b8d3-f009818b0cef)

**我们需要它的原因是什么?**

一般uniapp写样式的单位都是rpx，如果Tab直接生成的单位为rpx，开发效率大大提升。

**Comment by lqc520** [comment]
感谢老板的咖啡 这个功能下个版本发布

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.9-231.1/Uniapp-1.0.9-231.1.zip)
