### ISSUE TITLE
可不可以只在uniapp的工程中生效

### ISSUE THREAD

**Issue by aibayanyu20** [lqc520/uniapp-plugin#58]
**是关于什么的?**
可以不可以通过检测mainfast.json，只在uniapp的项目中生效，而不是所有的工程中生效

**我们需要它的原因是什么?**
运行一些其他的项目的时候，会拖慢工程加载速度

我相信这是Uniapp Tool的一个重要功能。 有一些用例:

* 案例一
* 案例二
* ...

如果有人同意我的观点，请在下面留下你的评论。或者只是竖起大拇指。

**Comment by lqc520** [comment]
项目是这个逻辑的呀 碰上什么问题了吗

**Comment by lqc520** [comment]
是什么功能出现在非uniapp项目？？

**Comment by aibayanyu20** [comment]
<img width="327" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/45655660/449d2758-9adb-4ae1-b4a9-ceeb422cd807">
这是我的一个普通的vite + ts的工程，不是uniapp的，正常不走插件的话应该这个会报黄吧，而且在建索引的时候有时候会卡住，禁用插件就好了，不知道这是什么情况

**Comment by lqc520** [comment]
优秀 这个被你抓到了 这个rpx是我唯一不判断uniapp工程 因为原生微信小程序也会用到 你使用了插件版本是什么 如果是最新版 不要开启子项目功能

**Comment by lqc520** [comment]
你提供一下 你的系统信息 cpu 内存 我考虑一下是否禁用rpx 主要是 wechat-mini-program-support 不维护了== 路上上不应该 我这台amd  4500U 的电脑都流畅

**Comment by aibayanyu20** [comment]
<img width="586" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/45655660/fd975b1a-75be-47fe-b96b-5316ae8a4900">
我这台电脑内存其实也不小，也可能是我电脑的问题，我的另一台m1的就没啥问题

**Comment by whiteS18** [comment]
> 优秀 这个被你抓到了 这个rpx是我唯一不判断uniapp工程 因为原生微信小程序也会用到 你使用了插件版本是什么 如果是最新版 不要开启子项目功能

你好，我已经开启了子项目功能，为什么还是会提示：不是uniapp项目无法运行,如果是uniapp项目请重启ide？uniapp项目是最后一个

<img width="397" height="122" alt="Image" src="https://github.com/user-attachments/assets/7e121467-7dd5-4958-8b14-c6df37bfe28e" />
