### ISSUE TITLE
行内rpx报错能否修复，看着难受。

### ISSUE THREAD

**Issue by jasonHG** [lqc520/uniapp-plugin#6]
![QQ截图20230503224827](https://user-images.githubusercontent.com/29171233/235952532-35139dbf-3b00-42a7-97d5-8ca43c4b3bcb.png)

**Comment by lnchengzi** [comment]
小问题 下午我发布一个版本给你

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.3.A/Uniapp-1.0.3.zip)

**Comment by jasonHG** [comment]
已测试，不报错了！感谢🙏
