### ISSUE TITLE
ts找不到uni变量

### ISSUE THREAD

**Issue by EgoElysia** [lqc520/uniapp-plugin#60]
**描述错误**
ts文件找不到uni变量 js文件正常
<img width="450" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/127327672/482a0562-1d84-417b-8b01-d49ec8aa4b81">

**使用的插件版本**
Uniapp Tool: 1.0.8-231.5
vue: 3 
project: hbx
ide: WebStorm 2023.2.1

**环境**
windwos11

**如何重现**

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by EgoElysia** [comment]
<img width="329" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/127327672/84dddff8-6c73-431e-bf90-ca87dbeb928b">

**Comment by lqc520** [comment]
hbx 如何创建vue3 ts项目

**Comment by lqc520** [comment]
这个是不支持的 需要支持ts 项目 用cli创建 
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/afe24a6c-f1da-4fdb-9a95-6e71398a11f2)

**Comment by lqc520** [comment]
使用ide创建的项目 创建后要重写打开一下项目 才能被识别为uniapp项目哈
