### ISSUE TITLE
code时变得非常的卡顿~~

### ISSUE THREAD

**Issue by T-99w** [lqc520/uniapp-plugin#61]
**描述错误**
PhpStorm 安装了 插件之后变得很卡顿
例如： 敲写代码的时候很卡顿，有时候会出现很严重滞后性

**使用的插件版本**
Uniapp Tool: 1.0.8-231.5
vue: 2
project: chbx
ide: PhpStorm 2023.2.2

**环境**
提供更多的信息:
比如:  win11
英特尔酷睿 i7-12700H
英伟达 RTX3060 Laptop

**如何重现**
重现行为的步骤:
emmmm不需要重现步骤，就装了插件打开ide一段时间就会变得非常的卡顿

**预期行为**
减少或消除卡顿即可~

**Comment by lqc520** [comment]
你这个配置不应该卡顿 我司8代i5机子 amd3500U 都正常 你先尝试一下删除.idea文件试试 不行的话再删除缓存 我们这边没用PhpStorm 如果还有问题 可以用ws试试

**Comment by T-99w** [comment]
@lqc520 尝试了清除缓存但是还是不行，看来要试试看ws

**Comment by lqc520** [comment]
ws 正常吗 如果还有问题继续反馈 我先关闭issues
