### ISSUE TITLE
启动项目报错 【Vue3 项目暂不支持当前小程序】

### ISSUE THREAD

**Issue by ipconfigall** [lqc520/uniapp-plugin#62]
**描述错误**
运行vue3小程序报错：Vue3 项目暂不支持当前小程序

![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/8968d583-1614-4d01-80de-b3080104af96)

**使用的插件版本**
Uniapp Tool: 1.0.9-231.2
vue: 3 
project: cli-js
ide: WebStorm 2023.2.2

**环境**
win11

**如何重现**
重现行为的步骤:
点击运行即报错

**Comment by ipconfigall** [comment]
使用上一版本正常

**Comment by lqc520** [comment]
没描述清楚 运行什么小程序

**Comment by lqc520** [comment]
manifest vueVersion截图一下 或者.idea uniappProjectData 截图一下

**Comment by lqc520** [comment]
感谢反馈 是有这个问题 先使用老版本

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.9-231.2/Uniapp-1.0.9-231.2.zip)
