### ISSUE TITLE
Webstorm输入中文时延迟很严重

### ISSUE THREAD

**Issue by shix9483** [lqc520/uniapp-plugin#63]
描述错误
WebStorm 安装了插件之后，输入中午卡顿。
例如： 敲写代码输入中午的时候很卡顿，会出现1s左右的延迟

使用的插件版本
Uniapp Tool: 1.0.8-231.5
vue: 3
ide: WebStorm 2023.2.1

环境
MacOS 13.5.2
Apple M1 Max
内存：32g

如何重现
重现行为的步骤:
安装了之后输入中文卡顿，卸载重启WebStorm后正常，再次安装还是卡顿。

预期行为
减少或消除卡顿即可~

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/de8d3755-bac9-4a7b-8068-be081de4abd0)
无法复现 看一下有没有更多人反馈这个问题

**Comment by lqc520** [comment]
可以尝试一下以下步骤 1、删除.idea 2、清理ide缓存 3、去设置关闭代码提示功能
