### ISSUE TITLE
直接用hbx创建的项目，非cli创建，'@/xxxx' 路径无法支持跳转

### ISSUE THREAD

**Issue by zencodex** [lqc520/uniapp-plugin#64]
**描述错误**
对bug的简明描述.

直接用hbx创建的项目，非cli创建，'@/xxxx' 路径无法支持跳转。

![image](https://github.com/lqc520/uniapp-plugin/assets/295317/957730ff-55c5-4d00-8de5-0facc80e79cb)

**使用的插件版本**
Uniapp Tool: 1.0.8-231.5
vue: 3 

**环境**
Mac osx, Intellij Ultimate 2023.2.2
项目为非cli 环境

**预期行为**
可以正常goto 跳转，目前无法跳转

**Comment by zencodex** [comment]
临时解决方案，代码根目录添加个 ide.config.js，内容如下：

```
System.config({
  "paths": {
    "@/*": "./"
  }
})
```


![image](https://github.com/lqc520/uniapp-plugin/assets/295317/c96a0662-b70f-4401-bc4e-fa8b51c6544e)

**Comment by lqc520** [comment]
这个是支持的 你你提供一下.idea下的 uniappprojectdata截图

**Comment by zencodex** [comment]
不知道是否和我这个工程结构有关，我是个多平台项目，uniapp 代码在src 这个目录里，外围目录是自己的结构。

![image](https://github.com/lqc520/uniapp-plugin/assets/295317/ca5d4d6d-c0ed-421a-9bc2-fed712e16364)

**Comment by lqc520** [comment]
有影响的 因为你的项目结构和cli的一样  所以被判定为cli 项目 所有不提供@解析
