### ISSUE TITLE
UniappPanel 有什么用处？

### ISSUE THREAD

**Issue by AkenClub** [lqc520/uniapp-plugin#65]
**描述错误**
如题，试着切换 vue 文件也没什么反应，也没有看到哪里有介绍
![image](https://github.com/lqc520/uniapp-plugin/assets/52781316/0015dbb4-f5fc-4d95-bf8b-f12c8bdfd070)

**使用的插件版本**
Uniapp Tool: 1.0.8-231.5
vue: 3 
project: cli-ts
ide: WebStorm 2023.2

**环境**
提供更多的信息:
比如:  win10
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:
打开 WS 就会有

**预期行为**
补充此 panel 的使用说明

**Comment by lqc520** [comment]
这个默认不主动打开的 这边是看微信小程序发行到官方后台的日志显示
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/b517fad6-46fd-42ff-a310-cca2e4ad9f50)
安装了插件就会显示

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/10e0d7e6-50ff-45ce-afa7-4fd6c6f3dd07)

**Comment by AkenClub** [comment]
> 这个默认不主动打开的 这边是看微信小程序发行到官方后台的日志显示 ![image](https://user-images.githubusercontent.com/33248612/270222408-b517fad6-46fd-42ff-a310-cca2e4ad9f50.png) 安装了插件就会显示

可能新安装没发现，刚看了一下在github release版本是有说到面板，但是在 WS 的插件更新说明貌似没有见到，建议 WS 插件更新说明同步 github 的比较好？
