### ISSUE TITLE
nvue文件的template中的变量没有代码提示，并且会提示“未解析的变量或类型”

### ISSUE THREAD

**Issue by kamiken233** [lqc520/uniapp-plugin#66]
**描述错误**
在nvue文件的template中使用变量没有代码提示，并且会提示“未解析的变量或类型”

![image](https://github.com/lqc520/uniapp-plugin/assets/96758300/27e3b58f-8114-47be-9eb1-b05ffab447be)

**使用的插件版本**
Uniapp Tool: 1.0.9-231.2
vue: 2
project: cli-js
ide: IDEA 2023.2.2

**预期行为**
和vue文件一样有代码提示

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.10.231.1/Uniapp-1.0.10-231.1.zip) 有问题可以继续反馈
