### ISSUE TITLE
请问支持安卓么编译到手机 开发预览么

### ISSUE THREAD

**Issue by linechengchen** [lqc520/uniapp-plugin#67]
**是关于什么的?**

**我们需要它的原因是什么?**

我相信这是Uniapp Tool的一个重要功能。 有一些用例:

* 案例一
* 案例二
* ...

如果有人同意我的观点，请在下面留下你的评论。或者只是竖起大拇指。

**Comment by lqc520** [comment]
可以实现 但是需要花一点时间 在没有赞赏的情况下 暂时不考虑 因为我司目前还没有这方面的需求哈
