### ISSUE TITLE
Type (e: any) => void is not assignable to type EventHandle

### ISSUE THREAD

**Issue by lCSSl** [lqc520/uniapp-plugin#69]
**描述错误**
对bug的简明描述.
所有uniapp内置组件的事件指向了一个未知的类型EventHandle
```Type (e: any) => void is not assignable to type EventHandle ```

<img width="581" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/77599000/dec152ef-45cb-427d-8326-ce8e4857440a">

将插件禁用后无报红

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: 1.0.9-231.2
vue: 3 
project: cli-ts
ide: WebStorm 2023.1.4

**环境**

![image](https://github.com/lqc520/uniapp-plugin/assets/77599000/3aeeb26d-370f-416d-a713-0f87131e839b)

**如何重现**
安装插件

**预期行为**
对你期望发生的事情进行清晰简洁的描述.
<img width="375" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/77599000/3bfd47d1-7e25-43d1-9961-8a1d54e90523">

**Comment by lCSSl** [comment]
强迫症犯了🫣

**Comment by lqc520** [comment]
标准是方法要加（）

**Comment by lqc520** [comment]
虽然可以不加
