### ISSUE TITLE
uniapp-cli方式创建的项目，无法通过插件启动

### ISSUE THREAD

**Issue by YaoShuwei** [lqc520/uniapp-plugin#7]
使用hx创建的项目，可以用此插件直接运行，但是通过uniapp-cli方式创建的项目，无法通过插件启动，提示
```
进程已结束,退出代码0
```

**Comment by lqc520** [comment]
cli方式用npm不是可以直接运行吗

**Comment by lqc520** [comment]
cli方式有必要用插件运行吗 有的话 我这边有空处理一下

**Comment by YaoShuwei** [comment]
> cli方式有必要用插件运行吗 有的话 我这边有空处理一下

是可以通过npm直接运行，不过想使用插件提供的发布并上传到微信后台的功能

**Comment by lqc520** [comment]
了解

**Comment by YaoShuwei** [comment]
> 了解

感谢作者大大

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.3.C/Uniapp-1.0.3.zip)
