### ISSUE TITLE
部分项目uni没有被识别出来

### ISSUE THREAD

**Issue by T-miracle** [lqc520/uniapp-plugin#70]
**描述错误**
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/37a783f2-56f2-4136-a4d4-e57ba367cf57)
部分项目uni没有被识别出来，我这边是H5正常，App不正常

**使用的插件版本**
Uniapp Tool: 1.0.9-231.2
vue: 2
project: hbx
ide: WebStorm 2023.2.2

**环境**
win11

**如何重现**
无

**预期行为**
uni被识别，有自动提示

**Comment by T-miracle** [comment]
@lqc520  后续发现：应该是整个App项目，所有HBX提示都失效了

**Comment by T-miracle** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/5750f8d1-517f-4a2d-bb2f-94499a41ca9e)

**Comment by lqc520** [comment]
看一下 
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/8a1a7df6-cc26-4386-ac82-065be3b5e9c7)
.idea文件夹下的这个数据

**Comment by T-miracle** [comment]
@lqc520 删除重启项目可行
