### ISSUE TITLE
Feature Request: Support for renderjs

### ISSUE THREAD

**Issue by cleverforest** [lqc520/uniapp-plugin#73]
希望增加对 renderjs （https://uniapp.dcloud.net.cn/tutorial/renderjs.html ）的支持。

**我们需要它的原因是什么?**

在下列代码中

```
<script module="test" lang="renderjs">
	export default {
		mounted() {
			// ...
		},
		methods: {
			// ...
		}
	}
</script>
```

其中的代码并不会被识别为 JavaScript 语言，目前只能开发时临时加上 lang="js" 解决。

**Comment by lqc520** [comment]
我看一下近期做个简单的支持

**Comment by lqc520** [comment]
这一块不需要插件支持 加个type就好啦

**Comment by lqc520** [comment]
有啥问题可以继续反馈
