### ISSUE TITLE
关于更新1.0.9和1.0.10版本插件nvue页面校验失效问题

### ISSUE THREAD

**Issue by zhuchonglin** [lqc520/uniapp-plugin#74]
## 通用说明

![QQ20231021-112931](https://github.com/lqc520/uniapp-plugin/assets/79825675/a345f8af-59ae-4e13-986d-938be22deb83)

**描述错误**
自从更新了一次1.0.9插件过后nvue页面的校验就失效了 原先正常无错误的页面开始提示各种错误，
例如自定义组件无法解析识别，变量无法解析 主要原因还是由于插件对nvue文件无效了 在vue文件中完全正常

**使用的插件版本**
Uniapp Tool: 1.0.10
vue: 3
project: cli-ts/hbx
ide: WebStorm 2023.2.3 

**环境**
比如:  macOS

**如何重现**
重现行为的步骤:
1. 创建nvue页面 随意编写一些script 和 template代码 并会发现 在template中使用script中的变量或方法会提示未解析，自然在template中使用自定义组件 也就导入到script中的组件 也是无法解析的 

**预期行为**
在未更新插件之前 使用的插件版本为1.0.7 编辑器版本为2023.1.4 nvue页面也能正常检测编写，从我更新了一次1.0.9插件过后nvue页面的检测就失效了，我回退编辑器版本以及插件版本还是存在问题。我还下载了作者提供的1.0.10版本还是无效

**Comment by lqc520** [comment]
经过检测 和插件版本没关系 和vuejs版本有关系 新版本的vuejs插件 很多地方判断文件后缀.vue的 并且vuejs插件是捆绑的 所以建议有用nvue的暂时用23.1.4版本
