### ISSUE TITLE
安装插件后编码输入删除等有卡顿，WebStorm-2023.2.3

### ISSUE THREAD

**Issue by adminxy** [lqc520/uniapp-plugin#76]
**描述错误**
安装插件后编码输入 删除 等操作有卡顿，安装插件后整个WebStorm的输入 删除等其他操作（包括但不限于 代码输入删除，git提交时写内容等WebStorm操作）都会有2秒左右的延迟

**使用的插件版本**
Uniapp Tool: 1.0.10-231.3
vue: 2
project: cli-js
ide: WebStorm 2023.2.3

**环境**
软：
   win11（22H2）
   WebStorm 2023.2.3
   Uniapp Tool: 1.0.10-231.3
   WebStorm内存：2048MB（设置过更大无明显改变）

硬：
  CPU：i5-9300H
  内存：16G
  显卡：GTX 1650

注：截止到此issues发布时，WebStorm和 Uniapp Tool均为最新版本

**如何重现**
重现行为的步骤:
1.安装插件 
2.重启WebStorm

**预期行为**
修复卡顿问题

**Comment by lqc520** [comment]
9300h 不应该呀 设置搜索 uniapp 把代码提示功能关闭看一下

**Comment by lqc520** [comment]
如果没有明显变化的话 1.删除.idea 文件 重开项目看看2.ide重置一下 排查ide错误 3.插件禁用 看一下效果 看一下哪一步有效果

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/7a792b24-6ac8-483b-ab7b-bf56635a5350)

**Comment by adminxy** [comment]
> 如果没有明显变化的话 1.删除.idea 文件 重开项目看看2.ide重置一下 排查ide错误 3.插件禁用 看一下效果 看一下哪一步有效果

好的，我去试下，稍后回复您

**Comment by adminxy** [comment]
> 9300h 不应该呀 设置搜索 uniapp 把代码提示功能关闭看一下

已关闭重新测试

**Comment by lqc520** [comment]
结果如何 因为ide是java写的 会比较吃性能啥的 卡顿出现可能有多方面 ide 电脑设备 插件 很多是升级ide导致的 ide会重新生成索引啥的 会卡顿 但是不是持续性的 除非ide索引崩了啥的  老旧设备都不建议持续升级ide  我公司本本amd cpu4500U inter-8265u 啥的都很流程

**Comment by adminxy** [comment]
> 如果没有明显变化的话 1.删除.idea 文件 重开项目看看2.ide重置一下 排查ide错误 3.插件禁用 看一下效果 看一下哪一步有效果

不好意思有点事情耽误了一会

 1.删除.idea 文件 重开项目看看 （无明显好转）
 2.ide重置一下 排查ide错误（无明显好转）
 3.插件禁用 （恢复正常）

单个字符操作的时候会造成卡顿，比如删除 按下删除按钮

**Comment by adminxy** [comment]
> 结果如何 因为ide是java写的 会比较吃性能啥的 卡顿出现可能有多方面 ide 电脑设备 插件 很多是升级ide导致的 ide会重新生成索引啥的 会卡顿 但是不是持续性的 除非ide索引崩了啥的 老旧设备都不建议持续升级ide 我公司本本amd cpu4500U inter-8265u 啥的都很流程

新版本的WebStorm确实硬件占用比较大 本身就内置了一些补全和后台代码分析，我也额外装了2款智能补全插件，可能是新版本不太兼容的问题吧，Uniapp Tool插件 我暂时先禁用了，后续有更新我会继续尝试，实在是不想吧WebStorm卸载了，重新安装，好多配置都要重新配置。

Uniapp Tool插件确实非常赞，提供了好多方便，可以不用打开HB就能运行编译。

Tip：感谢您辛苦开发Uniapp Tool插件 ，和回复我issues
         祝插件越来越好

**Comment by BillCooks** [comment]
IDEA2023.2.3同卡顿。我的配置是Macbook Pro 13 M1芯片16G的IDE内存配置3G，非常卡，无法正常输入文字,禁用插件后正常。

**Comment by lqc520** [comment]
如何复现呢 可以加入沟通群沟通 或者远程看一下

**Comment by BillCooks** [comment]
> 如何复现呢 可以加入沟通群沟通 或者远程看一下

启用插件之后就卡顿，没有其他操作，使用时间越长越卡。禁用之后就正常了。
![iShot_2023-10-26_11 13 18](https://github.com/lqc520/uniapp-plugin/assets/23414204/12945c9c-ad34-4665-952a-1e000467af22)

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/b6ac695e-511b-43d4-9761-fd228433b243)
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/66b9e5f4-04e0-4368-aaf9-7a97859cd4b1)
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/5e478e0f-992e-4c87-93e1-e2b08d0e2294)
我们这边公司的机子都很流畅 奇怪

**Comment by lqc520** [comment]
mac 哪一年的版本的

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/c0ceeaa5-d5fe-4a44-8eef-90027fe26bd8)
做个这个操作后看看

**Comment by lqc520** [comment]
可以进入插件沟通群 和我细化沟通一下

**Comment by BillCooks** [comment]
> IDEA2023.2.3同卡顿。我的配置是Macbook Pro 13 M1芯片16G的IDE内存配置3G，非常卡，无法正常输入文字,禁用插件后正常。

系统是MacOS 13.6，稍等下，我这边处理下事情，我先加下群

**Comment by jvhuaxia** [comment]
我也很卡 13900HX 使用了这个插件后 打字 CPU占用率能到80%
vue2
![image](https://github.com/lqc520/uniapp-plugin/assets/29006793/df4fdacc-2e8a-4338-b049-e984a59e3473)
![image](https://github.com/lqc520/uniapp-plugin/assets/29006793/39cb0853-6bde-4411-8cd7-25b133fa0699)
![image](https://github.com/lqc520/uniapp-plugin/assets/29006793/2e38ecbe-e208-4648-b101-92d8dc8d5e34)

**Comment by lqc520** [comment]
无法复现
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/bd7bbe16-086f-4fa0-ad87-f42baf75fdc1)

**Comment by lqc520** [comment]
使用新版插件看一下 如果为解决手动操作
![012f8baba664d33dec8b47b97c5fe5c](https://github.com/lqc520/uniapp-plugin/assets/33248612/8327f70b-d633-496a-bde9-866a523109ff)

**Comment by lqc520** [comment]
![8336c44c37560103f32beef4c9c2acf](https://github.com/lqc520/uniapp-plugin/assets/33248612/7c245da5-77a3-482f-8bd4-ef7fc4e17dad)
