### ISSUE TITLE
~/@ 无法识别为项目路径

### ISSUE THREAD

**Issue by huanglshu** [lqc520/uniapp-plugin#8]
~/@ 无法识别为项目路径

**Comment by lqc520** [comment]
是指哪一块 带图 目前仅识别import 这一块

**Comment by lqc520** [comment]
你这边是cli项目吧 已支持  [点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.3.C/Uniapp-1.0.3.zip)
