### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by LyingDoc** [lqc520/uniapp-plugin#82]
![图片](https://github.com/lqc520/uniapp-plugin/assets/131896721/9302026e-ec93-4f55-a3aa-08618c3d035c)
idea 2023.2.4

**Comment by lqc520** [comment]
打开其他项目会吗 或者说重新打开会吗

**Comment by lqc520** [comment]
[新版本试试](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.11-231.4/Uniapp-1.0.11-231.4.zip)
