### ISSUE TITLE
更新后css里background-image的url("")没提示了

### ISSUE THREAD

**Issue by JFPURE** [lqc520/uniapp-plugin#83]
**描述错误**
对bug的简明描述.

还请添加显示问题的屏幕截图.

**使用的插件版本**
Uniapp Tool: x.x.x 
vue: 2/3 
project: cli-js/cli-ts/hbx
ide: WebStorm 202x.x.x 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by JFPURE** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/22995116/ca4b1a50-7872-43d2-9921-20154165cc94)

**Comment by JFPURE** [comment]
强写报错，但是ui生效[doge]

**Comment by lqc520** [comment]
没提供环境
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/d061cb0b-f470-4f42-ba88-5ed74db535c1)

**Comment by JFPURE** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，来信已收到。无法及时回复您的邮件，深感歉意。

**Comment by lqc520** [comment]
不过新版本确实有问题 昨天中午已经测回发布 这两天会更新 先用老版本
