### ISSUE TITLE
[error] webstrom 2023.2.5 启动vue3项目 报错:Vue3 项目暂不支持当前小程序

### ISSUE THREAD

**Issue by ipconfigall** [lqc520/uniapp-plugin#86]
**描述错误**
启动VUE3项目报错

还请添加显示问题的屏幕截图.
![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/27893421-f532-4daa-a59d-a1da1316bd51)
![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/83d48390-504c-4322-96ac-389bd3470737)

**使用的插件版本**
Uniapp Tool: v1.0.11-231.4 
vue: 3 
project: cli-js/cli-ts/hbx
ide: WebStorm 2023.2.5 

**环境**
提供更多的信息:
比如:  win11/macOS
(欢迎其他信息帮助我们调试)

**如何重现**
重现行为的步骤:

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by lqc520** [comment]
你项目结构对不对 看一下.idea 的uniapptool

**Comment by ipconfigall** [comment]
项目结构没啥问题，在hbuilder中可以跑，
![image](https://github.com/lqc520/uniapp-plugin/assets/23722045/dcf02b55-9f6f-4afb-b04f-60437fd08d50)

**Comment by lqc520** [comment]
你是hx vue2 项目？  vue3项目应该还有vue 版本才对 你把.idea 删除了  重新打开项目

**Comment by lqc520** [comment]
如果是vue3 那就是项目没识别对 导致去调用vue2的启动

**Comment by lqc520** [comment]
![64403c544a20e3a1854bd5f6ded1441](https://github.com/lqc520/uniapp-plugin/assets/33248612/14c95e4e-99af-48e1-b1e5-105d7f526651)

**Comment by ipconfigall** [comment]
是vue3的项目，我根据这个配置文件修改之后，可以正常启动了

**Comment by lqc520** [comment]
这个是自动识别的 你的mainfest.json 没有定义vue版本吗 老项目？

**Comment by ipconfigall** [comment]
嗯，老项目，没有定义vue版本

**Comment by lqc520** [comment]
没其他问题 我这边就关闭了这个issues了
