### ISSUE TITLE
在idea中项目根目录下，有子文件夹为uniapp，怎么配置及编译uniapp文件夹中的uniapp工程

### ISSUE THREAD

**Issue by qc366** [lqc520/uniapp-plugin#9]
在idea中项目根目录下，有子文件夹为uniapp，怎么配置及编译uniapp文件夹中的uniapp工程

**Comment by lqc520** [comment]
当前版本不支持呢，只能打开子项目。后续版本会考虑支持一下哈

**Comment by qc366** [comment]
好的，谢谢，辛苦了。希望后续版本能改进。

**Comment by aimilin6688** [comment]
我也有同样的需求

**Comment by lqc520** [comment]
会出现 文件夹下的多个uniapp项目吗，一个项目倒是还好  如果是多个uniapp项目就要和npm一样 选择项目package文件一样 不然会影响到项目提示的根路径定位，出于这方面的考虑，暂时不考虑支持这一块哈
