### ISSUE TITLE
能否添加支持renderjs

### ISSUE THREAD

**Issue by Yueser** [lqc520/uniapp-plugin#91]
**是关于什么的?**
目前idea对<script lang="renderjs">没有任何支持，在需要使用renderjs的页面上写标签不会得到任何关于语言方面的帮助，连缩进都没有。

希望作者大大能够添加对renderjs的支持。
**我们需要它的原因是什么?**

如果有人同意我的观点，请在下面留下你的评论。或者只是竖起大拇指。

**Comment by jasonHG** [comment]
在 script 标签上加 type="javascript" 就有提示了

**Comment by lqc520** [comment]
#73 上面的打老说的对 加type就行
