### ISSUE TITLE
最新版本v1.0.12-231.1导致uniapp第三方组件不提示了

### ISSUE THREAD

**Issue by webzhouyan** [lqc520/uniapp-plugin#92]
使用最新的版本v1.0.12-231.1导致第三方uniapp组件不提示，缓存1.0.11版本正常。
正常的提示如下 
<img width="614" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/18736886/2bb1ddce-6d64-4763-9de4-303e171d4dd6">
<img width="633" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/18736886/67d367f6-9592-4eca-9826-69e6c6ff4280">
，而最新的版本无法正确提示，只提示为未知的html标签，使用组件时也不提示如下：
<img width="543" alt="image" src="https://github.com/lqc520/uniapp-plugin/assets/18736886/620af8e5-41e1-4987-9863-09e5e061ee6a">

**Comment by lqc520** [comment]
请按规范提问

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/900f02a8-e986-4a0b-b490-0d1f94466c47)
没有这些必要信息 没办法复现解答 处理

**Comment by lqc520** [comment]
我这边猜测你是cli 项目 并且uv 是通过npm 安装 这个是不行 因为easycom组件扫描我屏蔽了node模块 看来还是得开启来

**Comment by lqc520** [comment]
之前webstrom 能自动识别

**Comment by webzhouyan** [comment]
> 我这边猜测你是cli 项目 并且uv 是通过npm 安装 这个是不行 因为easycom组件扫描我屏蔽了node模块 看来还是得开启来

是的，我用的是cli项目，npm安装第三方组件

**Comment by lqc520** [comment]
晚上给你编译一个版本

**Comment by lqc520** [comment]
[点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.12-231.3/Uniapp-1.0.12-231.3.zip)

**Comment by webzhouyan** [comment]
> [点我下载](https://github.com/lqc520/uniapp-plugin/releases/download/v1.0.12-231.3/Uniapp-1.0.12-231.3.zip)
安装这个，已经恢复正常了
