### ISSUE TITLE
TS项目  在template中使用ref没有类型

### ISSUE THREAD

**Issue by haobarry** [lqc520/uniapp-plugin#93]
您不需要删除此评论部分，它在问题页面上是不可见的.

## 通用说明
使用的最新版

**描述错误**
在tempplate上使用的ref 或者reactive都没有设定的类型提示，现在显示都是any

**如何重现**
![图片](https://github.com/lqc520/uniapp-plugin/assets/9339292/03ea3fa8-d3a2-4ed9-9d55-e0648fe20f21)
没办法截到图  反正item就是个any类型 ，写的时候也没有ide的提示

**预期行为**
对你期望发生的事情进行清晰简洁的描述.

**Comment by lqc520** [comment]
无图无真相 我在ts项目正常
