### ISSUE TITLE
uni又无法识别了

### ISSUE THREAD

**Issue by T-miracle** [lqc520/uniapp-plugin#95]
**描述错误**
最近发现uni又没办法识别了，其他功能正常
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/d86f460d-1c1e-48d0-8ab1-847594a9296b)
按你之前说的，会生成这个文件
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/811f083f-aec5-4bee-a4fb-06de0b9cae00)
但是我发现，现在不会自动生成这个文件了，只有UniappTool.xml这个文件
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/9c63bc6d-b5b9-4385-b957-ee34b5e08df9)

**使用的插件版本**
Uniapp Tool: 1.0.12-231.3
vue: 2 
project: hbx
ide: WebStorm 2023.2.5 和 3.3

**环境**
win11

**如何重现**
从Git重新导入旧项目后

**预期行为**
uni正常识别

@lqc520

**Comment by lqc520** [comment]
打开这个uniappTool 看一下 这边最主要的就是这文件会标识是不是cli 项目 只有非cli项目才会提供 如果项目结构是标准的正常都会自动识别 不行的话重启一下项目 或者 删除.idea 会重新识别

**Comment by lqc520** [comment]
你可以加我微信沟通

**Comment by T-miracle** [comment]
> 打开这个uniappTool 看一下 这边最主要的就是这文件会标识是不是cli 项目 只有非cli项目才会提供 如果项目结构是标准的正常都会自动识别 不行的话重启一下项目 或者 删除.idea 会重新识别

目前已知 重启 和 删除.idea 都没有效果
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/1fafc784-5624-4be4-9366-85d204327440)
这是uniappTool.xml的信息

**Comment by lqc520** [comment]
应该和你项目结构有关系 你这边显示不是hx项目 你改成true就行

**Comment by T-miracle** [comment]
> 应该和你项目结构有关系 你这边显示不是hx项目 你改成true就行

改了也不行，放弃挣扎了，换成1.0.10版本了，暂顶着用了

**Comment by T-miracle** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/44044121/56f7eabf-3b98-464f-81e9-033042a9d416)
我这项目只有这个生成这个xml文件才能用，用生成UniappTool.xml的版本不得

**Comment by lqc520** [comment]
这个看你使用的插件版本 新版本是用uniappTool.xml 老的是用前面那个 这个是改版了 你这个目录结构是判定非hbx项目 所以不提供插件内置的types

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/e71ca28a-3d14-41fd-9715-1ce59edb2d35)
我这边vue2 hbx项目生成的文件 要是你有需要 我可以远程给你看看

**Comment by T-miracle** [comment]
> ![image](https://private-user-images.githubusercontent.com/33248612/301414211-e71ca28a-3d14-41fd-9715-1ce59edb2d35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzEyNTksIm5iZiI6MTcwNjc3MDk1OSwicGF0aCI6Ii8zMzI0ODYxMi8zMDE0MTQyMTEtZTcxY2EyOGEtM2QxNC00MWZkLTk3MTUtMWNlNTllZGIyZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDkzOWMwZTVhYTY0ZWY5MGQwYjA4OWI4OGMzNDBkNzFlM2Y3MTI5YTU5ZDJiMDJlNDE0MDQxM2E4YzY1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zjTLIUPLG-0unwe-34tRm8G7S94odY7TvAlA8u6DaPA) 我这边vue2 hbx项目生成的文件 要是你有需要 我可以远程给你看看

不用这么麻烦，老项目用用旧版插件能用也行了，太折腾也不好😂
