### ISSUE TITLE
选压缩代码无效

### ISSUE THREAD

**Issue by mmdlsu** [lqc520/uniapp-plugin#96]
![image](https://github.com/lqc520/uniapp-plugin/assets/57515771/1c03bc9e-d714-4a90-bb46-c21604008025)

**Comment by lqc520** [comment]
你是如何判定的？

**Comment by mmdlsu** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/57515771/17455efd-7c0d-44e7-b50d-2d24e76a9d63)
微信开发工具，依赖分析，压缩和不压缩对比大小

**Comment by mmdlsu** [comment]
当我用npm运行加上--minimize时主包大小才1.9MB
![image](https://github.com/lqc520/uniapp-plugin/assets/57515771/a0042340-9808-4a75-9ae4-902f59b7aac3)

**Comment by lqc520** [comment]
![image](https://github.com/lqc520/uniapp-plugin/assets/33248612/f1b84fd0-f9d8-4b47-9431-0227f83ef0f1)
我这边做的这个 运行时压缩代码 压缩多少取决于uniapp那边的处理

**Comment by mmdlsu** [comment]
要不要考虑--minimize这种压缩方式，这种小了很多

**Comment by lqc520** [comment]
是 这个估计是和发行的压缩率差不多
