### ISSUE TITLE
运行发布后不会自动打开微信开发者工具， 运行则会。  一直是这样吗？

### ISSUE THREAD

**Issue by grey6966** [lqc520/uniapp-plugin#97]
**使用的插件版本**
Uniapp Tool: 1.0.12
vue: 2
project: cli-js/cli-ts/hbx
ide: WebStorm 2023.3.3

**环境**
提供更多的信息:
比如:  win10

**预期行为**
运行 发布命令后 自动打开微信开发者工具

**Comment by lqc520** [comment]
是的 发行不调用启动开发者工具 你可以选择直接上传到微信后台
