### ISSUE TITLE
有关在webstorm中更新组件的问题

### ISSUE THREAD

**Issue by mhxy13867806343** [lqc520/uniapp-plugin#98]
**是关于什么的?**
<img width="1050" alt="QQ20240220-130220@2x" src="https://github.com/lqc520/uniapp-plugin/assets/4418166/d8b12205-2bc4-4f06-b316-ca652d77810a">
是这样 的，在hbuerx里面，右键对uni_modules的时候，会出现截图的情况，也希望在ws里面支持，可以从插件市场更新所有插件 这个功能

**我们需要它的原因是什么?**

我相信这是Uniapp Tool的一个重要功能。 有一些用例:

* 案例一
* 案例二
* ...

如果有人同意我的观点，请在下面留下你的评论。或者只是竖起大拇指。

**Comment by lqc520** [comment]
这个是很好的想法 但是不太好实现 我研究一下哈
